### ISSUE TITLE
Use the stencil buffer outside the scene view canvas for editing

### ISSUE THREAD

**Issue by 32678** [mob-sakai/SoftMaskForUGUI#100]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe what help do you need**
A description of the question.
Hello, I have a problem about showing masked image.

Before explain, I write about mask hierarchy
[Canvas] - [ScreenSpace - Camera]
 -[GameObject1]
  -[GameObject2]
   -[GameObject3]
    -[MaskImage] -> I gave softmask component here
     -[MaskedImage] -> I gave softmaskable component

I completed soft mask setting, but [MaskedImage] didn't show on view.
I could see only [MaskImage] on the view. 

And I tried to find resolution. I changed variety relevant settings and checked It's result.
finally, I found several hints about this problem.

-[MaskedImage] was shown within some boundary.
-And boundary was canvas resolution size.

And now I have a question.
-Can I make the [MaskedImage] visible outside the canvas resolution size area?
(Because of rules, resolution size cannot be changed)

*There may be weird sentences using the translator, I would be grateful if you could understand my situation.

**Additional context**
Add any other context or screenshots about the question here.
![01](https://user-images.githubusercontent.com/55367723/92392807-d5d34e80-f159-11ea-97c1-2185a325cf7e.png)
-[MaskedImage] showing just in that boundary.

![02](https://user-images.githubusercontent.com/55367723/92392811-d79d1200-f159-11ea-84f0-9b3160a58832.png)
-This is [MaskImage} setting.

![03](https://user-images.githubusercontent.com/55367723/92395725-c4d90c00-f15e-11ea-80c5-8b30b75ab709.png)
-This is [MaskedImage} setting.

**Comment by mob-sakai** [comment]
@32678 
Are you talking about the scene view, not the game view?
That's a spec, but you find it inconvenient when editing in scene view, right?

**Comment by 32678** [comment]
> @32678
> Are you talking about the scene view, not the game view?
-> Yes, I'm talking about the scene view.
     Actually, I can't check if it's visible outside of the resolution in the game view.
     Our project is a way to illuminate the screen while moving the camera on a long horizontal screen.
     If this doesn't seem to work, does it actually appear in the developed app?

> That's a spec, but you find it inconvenient when editing in scene view, right?
-> Yes, Is this an unavoidable part according to the specifications?

**Comment by mob-sakai** [comment]
OK.
I will fix it later.

[WIP] The stencil buffer will be used outside the scene view canvas.

![](https://user-images.githubusercontent.com/12690315/92423279-92a9c780-f1bb-11ea-8bef-c9a8c48089fb.png)
![](https://user-images.githubusercontent.com/12690315/92423119-d6500180-f1ba-11ea-92f6-28061a88e057.gif)

**Comment by WintorJesseVanBloemenhuis** [comment]
Ran into the same issue and it doesn't seem to work in v1.0.2 in Unity 2020.3.

![image](https://user-images.githubusercontent.com/92723189/184268599-83575a23-f304-4076-807d-1d66b9d0c967.png)
