### ISSUE TITLE
Unable to modify custom shader's properties in scripts' update?

### ISSUE THREAD

**Issue by udvaritibor** [mob-sakai/SoftMaskForUGUI#101]
I've managed to set up my shader's SoftMaskable version. But now I can't change the shader's properties at runtime.

```
Shader "Hidden/Custom/UI/Grayscale (SoftMaskable)"
{
	Properties
	{
		[PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
		_Color ("Tint", Color) = (1,1,1,1)
		
		_StencilComp ("Stencil Comparison", Float) = 8
		_Stencil ("Stencil ID", Float) = 0
		_StencilOp ("Stencil Operation", Float) = 0
		_StencilWriteMask ("Stencil Write Mask", Float) = 255
		_StencilReadMask ("Stencil Read Mask", Float) = 255

		_EffectAmount ("Effect Amount", Range (0, 1)) = 1.0
		_BrightnessAmount ("Brightness Amount", Range(0.0, 3)) = 1.0

		_ColorMask ("Color Mask", Float) = 15
	}
        ...
```

And this is how I set properties in Update (for a short period of time):

`LevelImage.material.SetFloat("_EffectAmount", amount);`

If I click on the Material in the object's Renderer itself, it shows the correct effect amount, but under the object, it displays the Hidden Soft Maskable material, with unchangeable default properties.

How could I fix this?

Thanks in advance! :)

**Comment by mob-sakai** [comment]
@udvaritibor 

Please try `CanvasRender.GetMaterial()` to get the material for rendering.

```cs
LevelImage.canvasRenderer.GetMaterial().SetFloat("_EffectAmount", amount);
```

**Comment by udvaritibor** [comment]
@mob-sakai For some reason CanvasRenderer.GetMaterial() returns null :\

**Comment by mob-sakai** [comment]
@udvaritibor 
Hmm...
In the first frame, it may return null.

**Comment by udvaritibor** [comment]
@mob-sakai It's constantly null, while LevelImage.material is constantly not null. Here's the setup: (Where the Image component is LevelImage)

![image](https://user-images.githubusercontent.com/9115891/93119395-0703cf80-f6c2-11ea-89e9-c7ad75199925.png)

**Comment by udvaritibor** [comment]
@mob-sakai Thanks, yes, it's only null at the first frame. :)
(In the last (now deleted) comment I said that it's constantly null, and it was null only due to an issue on my side)

**Comment by mob-sakai** [comment]
Use `v1.0.0-preview.11` and (Graphic.materialForRendering property)[https://docs.unity3d.com/2018.4/Documentation/ScriptReference/UI.Graphic-materialForRendering.html].
