### ISSUE TITLE
UPM issue

### ISSUE THREAD

**Issue by ChanUkLee** [mob-sakai/SoftMaskForUGUI#102]
Asset Packages/com.coffee.softmask-for-ugui/Samples has no meta file, but it's in an immutable folder. The asset will be ignored.

**Environment (please complete the following information):**
 - Version 1.0.0
 - Unity version: 2019.4.10f1

**Comment by mob-sakai** [comment]
@ChanUkLee 
Do you use a path query in package url?
`"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/SoftMaskForUGUI#develop",`

Try deleting the path query:
`"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git",`

**Comment by ChanUkLee** [comment]
@mob-sakai 
I'm using openupm.
`openupm add com.coffee.softmask-for-ugui`

This is my manifest.json.
`{
  "dependencies": {
    ...
    "com.coffee.softmask-for-ugui": "1.0.0-preview.9"
    ...
  },
  "scopedRegistries": [
    {
      "name": "package.openupm.com",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.coffee.softmask-for-ugui",
        "com.openupm"
      ]
    }
  ]
}`

Also, i can find "Samples" directory without meta file in package dir.

**Comment by mob-sakai** [comment]
@ChanUkLee 
Thanks for the reply.
I've created an issue on OpeUPM.
https://github.com/openupm/openupm/issues/1315

Until this issue is resolved, please use a git-based url instead:
`"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git",`
