### ISSUE TITLE
Failing to open source file SoftMask.cginc 

### ISSUE THREAD

**Issue by RodrigoManuelPerez** [mob-sakai/SoftMaskForUGUI#105]
Hi this is my first issue ever so i'll try to do it right

The thin is that as soon as I try to attach the components SoftMaskeable and SoftMask, it throws me a shader error on the editor:

Shader error in 'Hidden/UI/Default (SoftMaskable)': failed to open source file: 'Packages/com.coffee.softmask-for-ugui/Shaders/SoftMask.cginc' at line 59 (on d3d11)

This results into a missing texture and the mask image turns into the missing texture pink color

I'm working on Standalone(Windows/Mac/Linux) on Unity 2019.3.0f6 and I tried the last 2 release versions

**Comment by mob-sakai** [comment]
@RodrigoManuelPerez 
Thank you for reporting.
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
@RodrigoManuelPerez 
It does not reproduce in my environment.
Did you install the package via upm?

**Comment by RodrigoManuelPerez** [comment]
@mob-sakai 
Hi I tried again and it works fine, well i have to learn how to use it properly but it works with no errors. I tried to install it through upm but it was my first time so i guess a made some mistake

Thank you very much and I appreciate the support!! ^^

**Comment by mob-sakai** [comment]
I’m happy to hear that!

**Comment by tomkail** [comment]
Sorry to resurrect this thread, but we're seeing this too. The folder in Packages appears to be called UI Soft Mask so I can see why it would fail to reference Packages/com.coffee.softmask-for-ugui. I've tried uninstalling/reinstalling without success.

**Comment by NikitaKirakosyan** [comment]
> > > Sorry to resurrect this thread, but we're seeing this too. The folder in Packages appears to be called UI Soft Mask so I can see why it would fail to reference Packages/com.coffee.softmask-for-ugui. I've tried uninstalling/reinstalling without success.
> > 
> > 
> > Just change the link to the right location. I had mine inside the asset folder.
> 
> What is the right location?

You probably don't need it anymore, but try this:
1) in UPM select UI Soft Mask
2) in the additional window on the right there are tabs like "Description", "Version History", "Dependencies", "Samples"
3) select the "Samples" tab
4) click import wherever needed within the tab
![image](https://github.com/mob-sakai/SoftMaskForUGUI/assets/84707926/33f262ba-0e27-4c29-8f12-53af55ded209)

I hope it will help other users

**Comment by NikitaKirakosyan** [comment]
> > > > Sorry to resurrect this thread, but we're seeing this too. The folder in Packages appears to be called UI Soft Mask so I can see why it would fail to reference Packages/com.coffee.softmask-for-ugui. I've tried uninstalling/reinstalling without success.
> > > 
> > > 
> > > Just change the link to the right location. I had mine inside the asset folder.
> > 
> > 
> > What is the right location?
> 
> You probably don't need it anymore, but try this:
> 
> 1. in UPM select UI Soft Mask
> 2. in the additional window on the right there are tabs like "Description", "Version History", "Dependencies", "Samples"
> 3. select the "Samples" tab
> 4. click import wherever needed within the tab
> 
> ![image](https://user-images.githubusercontent.com/84707926/261851514-33f262ba-0e27-4c29-8f12-53af55ded209.png)
> 
> I hope it will help other users

@mob-sakai 
@ducloc96
