### ISSUE TITLE
Masked image disapear on resolution change

### ISSUE THREAD

**Issue by plyoung** [mob-sakai/SoftMaskForUGUI#106]
The masked image disappears when you change the resolution in-game. 
Tested a Windows build.

Create a build of the attached project.
You will see a green rectangle masked by a white circle.
Change resolution and observe the green image is gone.

[TEST.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/5301154/TEST.zip)

**Comment by mob-sakai** [comment]
@plyoung 
The issue is reproduced in my environment.

In window mode: Working fine.
In full-screen mode: Green rectangle is disappeared.

In full screen, I noticed that `SoftMaskable` was not refreshing on changed the screen resolution.

**Comment by mob-sakai** [comment]
@plyoung 
Workaround: It worked correctly when `Desampling Rate` (downsampling rate) was set to `None`.

![image](https://user-images.githubusercontent.com/12690315/94792649-39c4fc00-0414-11eb-9afe-67488b9e42db.png)

**Comment by mob-sakai** [comment]
@plyoung 
Try to use `1.0.0-preview.13`

**Comment by piotrshishkov** [comment]
Not fixed in latest version, even if Desampling Rate set to None

**Comment by Luanrobs** [comment]
@mob-sakai

Hello, after spending some time examining the code, I was able to devise a solution. Please make the following modification to the GetDownSamplingSize function within SoftMask.cs.

![MaskFix](https://user-images.githubusercontent.com/53914581/227223076-c7222b43-7c8f-443c-8e4a-0f77a0ac5e14.png)

**Comment by mob-sakai** [comment]
Thanks a lot!

**Comment by mob-sakai** [comment]
@Luanrobs 
Are the differences you expect to see as follows?
```
@@ -663,12 +663,6 @@ namespace Coffee.UISoftMask
             }
             else
 #endif
-            if (Screen.fullScreenMode == FullScreenMode.Windowed)
-            {
-                w = Screen.width;
-                h = Screen.height;
-            }
-            else
             {
                 w = Screen.currentResolution.width;
                 h = Screen.currentResolution.height;
```

**Comment by Luanrobs** [comment]
That's it, by removing those checks I was able to solve the problem I was having here. I'm not sure if this could end up affecting something else, I would have to test it.

**Comment by vgabler** [comment]
This issue is still occurring today.
I'm using Unity 2020.3.18f1, softmask v1.0.2

This code did solve the issue for me!  Thanks, @Luanrobs !

> @mob-sakai
> 
> Hello, after spending some time examining the code, I was able to devise a solution. Please make the following modification to the GetDownSamplingSize function within SoftMask.cs.
> 
> ```
> private static void GetDownSamplingSize(DownSamplingRate rate, out int w, out int h)
>         {
>             w = Screen.currentResolution.width;
>             h = Screen.currentResolution.height;
> 
>             if (rate == DownSamplingRate.None)
>                 return;
> 
>             var aspect = (float) w / h;
>             if (w < h)
>             {
>                 h = Mathf.ClosestPowerOfTwo(h / (int) rate);
>                 w = Mathf.CeilToInt(h * aspect);
>             }
>             else
>             {
>                 w = Mathf.ClosestPowerOfTwo(w / (int) rate);
>                 h = Mathf.CeilToInt(w / aspect);
>             }
>         }
> ```
