### ISSUE TITLE
[v1] Weird Rendering with world canvases when resizing or moving

### ISSUE THREAD

**Issue by TheXRMonk** [mob-sakai/SoftMaskForUGUI#108]
**Describe the bug**
Basic resizing or moving of a world canvas breaks the masks. Saving the scene updates and sometimes fixes it, but not always

**To Reproduce**
Setup some world canvas with a mask and something masked. Then resize or move it.

**Screenshots**
Before moving;
![image](https://user-images.githubusercontent.com/54309738/102783041-a65bf100-439a-11eb-890b-19b6a16df085.png)

After moving on z axis:
![image](https://user-images.githubusercontent.com/54309738/102783168-d1464500-439a-11eb-8d6c-3f4ca36e3e96.png)

Small video:
https://user-images.githubusercontent.com/54309738/102783605-76611d80-439b-11eb-9863-25c8cbdcaf31.mp4

**Environment:**
 - Version 1.0.0-preview 14
 - Platform: Editor/windows
 - Unity version: 2020.1.16f1
 - Build options: .Net 4.x, URP

**Comment by mob-sakai** [comment]
@VirsabiMunk 
Thank you for your reporting!

**Comment by pajama** [comment]
I had similar behavior. Was resolved by setting the event camera on the canvas.

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
