### ISSUE TITLE
Huge memory leaks TempBuffer.RenderTexture using softmask

### ISSUE THREAD

**Issue by novavision** [mob-sakai/SoftMaskForUGUI#109]
**Describe the bug**
Using SoftMasks in multiple screens in the game cause 150mb memory leak creating up to 50 render textures.

**To Reproduce**
Create multiple scroll views with 1-2 softmask images in each scrollable item.

**Expected behavior**
SoftMask not spam the  RenderTextures for each UI image with this component attached

**Screenshots**
<img width="1127" alt="Memory Profiler" src="https://user-images.githubusercontent.com/5512405/103474919-568e1880-4de3-11eb-8d99-73f33edd8e76.png">

**Environment (please complete the following information):**
 - Version [1.0.0-preview.14]
 - Platform: [Editor(Mac), iOS, Android]
 - Unity version: [e.g. 2020.1.17]
 - Build options: [IL2CPP, .Net 4.x]

**Additional context**

**Comment by mob-sakai** [comment]
@novavision 
Thank you for your reporting!

**Comment by evgeny-detkov** [comment]
Hey! We also have this problem. Please resolve the issue as soon as possible. Thank!

![profiler](https://user-images.githubusercontent.com/5319984/108341776-15af5f00-71eb-11eb-8901-90a57a22ba90.jpg)

**Comment by mob-sakai** [comment]
@evgeny-detkov @novavision 
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by evgeny-detkov** [comment]
@mob-sakai [LINK to test project](https://drive.google.com/file/d/1EdPQjvG-HseN2p1dRiOUZI7j8EFjXyzK/view?usp=sharing)

![image](https://user-images.githubusercontent.com/5319984/108355932-7f843480-71fc-11eb-9764-a62d47c2806b.png)

**Comment by mob-sakai** [comment]
@evgeny-detkov 
Thanks!

**Comment by mob-sakai** [comment]
@evgeny-detkov 
Multiple `SoftMask` components can share a single `RenderTexture`. Set up as follows:

![](https://user-images.githubusercontent.com/12690315/108467411-811b2e80-72c8-11eb-8a50-ea9f2c246167.png)


1. Select `Canvas/Scroll View/Viewport` game object and convert `Mask` component to `SoftMask` component from the context menu (`Convert to SoftMask`).
![](https://user-images.githubusercontent.com/12690315/108466109-78c1f400-72c6-11eb-9617-a896ab2e4b4d.png)
2. Fix 2 warnings.
![](https://user-images.githubusercontent.com/12690315/108466454-0867a280-72c7-11eb-93ef-a827be41ad1a.png)
3. Select `Canvas/Scroll View/Viewport/Content/GameObject ~ GameObject(97)` game objects and disable `Ignore Parent` and `Part Of Parent`.
![](https://user-images.githubusercontent.com/12690315/108467078-fa665180-72c7-11eb-9360-fcf935b2f42e.png)
4. That's all. :tada: 
![](https://user-images.githubusercontent.com/12690315/108467639-e96a1000-72c8-11eb-97d3-ab87071de249.png)

**Comment by novavision** [comment]
Thanks for explanation, I tried adapt your test scene to my hierarchy and it seems working fine. But I got question regarding to my case (I think it's pretty common UI structure):

I got 20+ screens, some of them has `ScrollRect` (~10) with `SoftMask` used in their children. Some screens has >1 `ScrollRect`. 
In terms of memory optimization, using your solution above, it's better to attach the `SoftMask` to the parent (screen object).
Even in this case I will have ~10 `RenderTexture` in buffer. What if I add 'SoftMask` it to most parent object? Like main `Canvas`? Will it negatively affect to the performance?

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by novavision** [comment]
It's not an issue, it's a question, related to buffered RenderTexture optimization.

**Comment by mob-sakai** [comment]
If the SoftMask buffers are the same size, they will be recycled.
