### ISSUE TITLE
[v1] Texture unsettable in the Material?

### ISSUE THREAD

**Issue by Noblauch** [mob-sakai/SoftMaskForUGUI#111]
Hi, we are using softmask for a while now.
I now came to a point where the texture must be defined in our Material, but the required [PerRendererData] flag that softmask depends on inside the Shader prevents the appearing of the texture picker inside the Material settings.
I uncommented this, set the texture and reset the declaration and it works. So there must be a way to resolve this issue, how would I make this possible?

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
