### ISSUE TITLE
Pink TextMeshPro UGUI text if SoftMaskable is applied

### ISSUE THREAD

**Issue by novavision** [mob-sakai/SoftMaskForUGUI#114]
**Describe the bug**
Using TextMeshPro 3.x.x the text material rendered in pink color. I searched for similar issues in closed tickets and found this one #99 where says this issue is fixed in preview 6, but it still exists in preview 14

**To Reproduce**
1. Add TextMeshProUGUI text in maskable element
2. Click Fix on the main parent SofMask component to auto set SoftMaskable component to all children

**Expected behavior**
TextMeshProUGUI component displayed correctly.

**Screenshots**
![SampleScene - TriviaFight - iOS - Unity 2020 1 17f1  PREVIEW PACKAGES IN USE   Metal  2021-02-25 22-39-09](https://user-images.githubusercontent.com/5512405/109172760-1719f200-77be-11eb-88e1-5319fdcad532.png)

**Environment (please complete the following information):**
 - Version: "com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git#1.0.0-preview.14"
 - Platform: Mac Editor, iOS, Android builds
 - Unity version: 2020.1.17f1
 - Build options: IL2CPP, .Net 4.x

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by novavision** [comment]
Weird, but I tried to reproduce it in empty project, importing my font assets I use in the main project, but it worked fine.
Will try to investigate this case, what exactly differ

**Comment by novavision** [comment]
Doing some more testing, I found that it's not necessary to click `Fix` on the parent `SoftMask` component. This means, masking works pretty well without attaching `SoftMaskable` to each `Graphic` components. 
Is there any reason I don't know why it MUST be attached? I tried it only in simple test scene, not in my project yet.

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by novavision** [comment]
Check it [here](https://www.dropbox.com/s/h8k9ecype4059uf/sample%20project.zip?dl=0) please

**Comment by mob-sakai** [comment]
See [here](https://github.com/mob-sakai/SoftMaskForUGUI#usage-with-textmeshpro) and import `TextMethPro Support`.

![](https://user-images.githubusercontent.com/12690315/109300564-016a0280-787a-11eb-99a3-32918ceb73b2.png)

Then fix `TMP_SDF (SoftMaskable).shader` and `TMP_SDF-Mobile (SoftMaskable).shader` according to the error.

![](https://user-images.githubusercontent.com/12690315/109301392-3b87d400-787b-11eb-9da1-7d8cca1f17b8.png)
```
// Remove "Resources/" in path
// #include "Assets/TextMesh Pro/Resources/Shaders/TMPro_Properties.cginc"
#include "Assets/TextMesh Pro/Shaders/TMPro_Properties.cginc"
// #include "Assets/TextMesh Pro/Resources/Shaders/TMPro.cginc"
#include "Assets/TextMesh Pro/Shaders/TMPro.cginc"
```

🎉 
![](https://user-images.githubusercontent.com/12690315/109302036-1b0c4980-787c-11eb-8be2-9af758479f5e.png)

**Comment by novavision** [comment]
Yes, this works now. Sorry, I didn't see such instructions in docs
