### ISSUE TITLE
[v1] Big performance hit (CPU + GC Alloc) coming from SoftMaskable.UpdateMaterialForSceneView

### ISSUE THREAD

**Issue by oxysoft** [mob-sakai/SoftMaskForUGUI#115]
![image](https://user-images.githubusercontent.com/3945277/110691405-1bc5a980-81b3-11eb-98d8-ee5ad424b3b3.png)

This is for ~300 SoftMaskables. All of the allocation comes from accessing `mat.shader.name`, and then there's the  "Set view and projection matrices" part as well which takes a decent amount of time. I am aware that function  runs only in editor, but this performance hit is still pretty harsh for productivity.

Perhaps you could restrict this function to running only when the SceneView is visible in the editor? Currently, it will run whether the SceneView is visible or not.

**Comment by mob-sakai** [comment]
@oxysoft 
Thank you for your reporting!

**Comment by oxysoft** [comment]
Any idea on when this may be looked at?

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
