### ISSUE TITLE
[v1] Masked images disappear on resize if there are images using the normal Unity mask

### ISSUE THREAD

**Issue by SvenRH** [mob-sakai/SoftMaskForUGUI#117]
**Describe the bug**
Softmaskable images disappear when game is resized when there are are images using the unity mask in the scene.

**To Reproduce**
1. Create new project, add Softmask and Demo
2. Open Soft Mask Demo
2. Resize Game View
3. masked images disappear

If the images using the 'normal' Unity mask are removed, everything seems to be fine.

**Expected behavior**
SoftMask should work when there are Unity Masks used in the scene.

**Screenshots**
![image](https://user-images.githubusercontent.com/37126213/112523486-182f4680-8d9f-11eb-9902-088a03044ba6.png)

**Environment (please complete the following information):**
 - Version 1.0.0
 - Platform: Editor (Windows), Standalone(Windows, Android) 
 - Unity version: 2020.3.0 (also happened with several 2020.2.x versions)
 - Build options: Defaults - New Project with 2D template

**Comment by SvenRH** [comment]
The issue seems to be that the RenderTexture is recreated on resize, but the new Texture isn't applied to the SoftMaskable.

A possible fix would be to add the softMaskBuffer to the  _effectMaterialHash calculation, but it seems like it would be a better idea to just set the Texture outside of MaterialCache (seems like overkill to recreate the material just for that).

**Comment by NotGeniusy** [comment]
I made a script that disables and re-enables SoftMasks to refresh them. It worked for me. 
Just place this script to every GameObject with SoftMask.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Coffee.UISoftMask;

public class SoftMaskFixer : MonoBehaviour
{
    private SoftMask softMask;

    private List<GameObject> childs = new List<GameObject>();

    private void OnRectTransformDimensionsChange()
    {
        if(softMask == null)
        {
            softMask = GetComponent<SoftMask>();

            foreach(Transform child in transform)
            {
                childs.Add(child.gameObject);
            }
        }

        if(gameObject.activeInHierarchy)
        {
            StartCoroutine(Fix());
        }
    }

    private IEnumerator Fix()
    {
        foreach(GameObject child in childs)
        {
            child.SetActive(false);
        }

        softMask.enabled = false;

        yield return new WaitForSeconds(0.01f);

        softMask.enabled = true;

        foreach (GameObject child in childs)
        {
            child.SetActive(true);
        }
    }
}
```

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)

**Comment by mushakushi** [comment]
I'm able to reproduce the same issue on 2.2.0 with Unity version 2022.3.16f. There are some instances where the image does not fully disappear or flickers when the canvas is actively being resized.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
- Does it occur only in the editor?
- Can I attach videos or gifs?

**Comment by mushakushi** [comment]
> Does it occur only in the editor?
Yes and regardless of if playmode is enabled. 

> Can I attach videos or gifs?
https://github.com/user-attachments/assets/3f733bc2-a361-45b2-a737-8adeb9a0eeb5

Thank you for your quick support!

**Comment by mob-sakai** [comment]
@mushakushi 
I created a new issue: #184
