### ISSUE TITLE
[v1] Images are not updated when alpha is changed by animation 

### ISSUE THREAD

**Issue by marcelopapelgames** [mob-sakai/SoftMaskForUGUI#118]
I am using the SoftMask to fade in some UI Images. I added SoftMask to a parent object, where an Animation changes the value of alpha along the time. There are children objects with images and SoftMaskables that should "fade in" with the animation but nothing happens. It seems one value for alpha is used for rendering, the value is constantly updated - as seen in debug - but the images are not updated. 

If I add code to update() method to verify changes in the alpha value and then call OnValidate(), the magic happens. I did for test purposes only.

https://youtu.be/XSFi4rIt_Z8 

Version: Unity 2020

**Comment by marcelopapelgames** [comment]
I think I found a fix, by adding this to SoftMask.cs:

```
        protected override void OnDidApplyAnimationProperties()
        {
            hasChanged = true;
        }
```

**Comment by KadynCBR** [comment]
This helped my issue thanks! If there's a more proper way to do animations using softmask I'd like to know

**Comment by KimYC1223** [comment]
@marcelopapelgames 

Thank you so much... I wasted hours on this problem.

But this fix completely eliminated my issue. thank you!

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
