### ISSUE TITLE
[v1] Preview the masked elements in Scene view

### ISSUE THREAD

**Issue by victor-kallai** [mob-sakai/SoftMaskForUGUI#119]
Would it be possible to preview the masked sprites and TMP labels in the Scene view?

At the moment, I can only see the mask working in the editor game and in play mode.
If I am editing some UI prefabs in isolation, the mask is not visible, as the prefab si not rendered on the Game view.

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
