### ISSUE TITLE
Error on shaders for TextMeshPro 3.0.x

### ISSUE THREAD

**Issue by victor-kallai** [mob-sakai/SoftMaskForUGUI#120]
The TMP essential resources from version 3.0.x have a different folder path for the Shaders folder.

TMP_SDF (SoftMaskable).shader and TMP_SDF-Mobile (SoftMaskable).shader need to change the TMP imports to:

`#include "Assets/TextMesh Pro/Shaders/TMPro_Properties.cginc"
#include "Assets/TextMesh Pro/Shaders/TMPro.cginc"`

**Comment by mob-sakai** [comment]
Sorry for my late reply.
It has be released in [v1.0.2](https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/1.0.2).

Thanks to all of you for your cooperation! 👍
