### ISSUE TITLE
[v1] ArgumentException: RenderTextureDesc width must be greater than zero.

### ISSUE THREAD

**Issue by xaero84** [mob-sakai/SoftMaskForUGUI#121]
Getting this exception every second in Unity 2020.3.0f1:

ArgumentException: RenderTextureDesc width must be greater than zero.
Parameter name: desc.width
UnityEngine.RenderTexture.ValidateRenderTextureDesc (UnityEngine.RenderTextureDescriptor desc) (at <42a5878ce129403083acccf18e43363f>:0)
UnityEngine.RenderTexture.GetTemporary (UnityEngine.RenderTextureDescriptor desc) (at <42a5878ce129403083acccf18e43363f>:0)
UnityEngine.RenderTexture.GetTemporaryImpl (System.Int32 width, System.Int32 height, System.Int32 depthBuffer, UnityEngine.Experimental.Rendering.GraphicsFormat format, System.Int32 antiAliasing, UnityEngine.RenderTextureMemoryless memorylessMode, UnityEngine.VRTextureUsage vrUsage, System.Boolean useDynamicScale) (at <42a5878ce129403083acccf18e43363f>:0)
UnityEngine.RenderTexture.GetTemporary (System.Int32 width, System.Int32 height, System.Int32 depthBuffer, UnityEngine.RenderTextureFormat format, UnityEngine.RenderTextureReadWrite readWrite) (at <42a5878ce129403083acccf18e43363f>:0)
Coffee.UIExtensions.SoftMask.get_softMaskBuffer () (at Assets/Coffee/UIExtensions/SoftMaskForUGUI/Scripts/SoftMask.cs:177)
Coffee.UIExtensions.SoftMask.UpdateMaskTexture () (at Assets/Coffee/UIExtensions/SoftMaskForUGUI/Scripts/SoftMask.cs:530)
Coffee.UIExtensions.SoftMask.UpdateMaskTextures () (at Assets/Coffee/UIExtensions/SoftMaskForUGUI/Scripts/SoftMask.cs:479)
UnityEngine.Canvas.SendWillRenderCanvases () (at <a8e296dc7c7b4e92800d9e996ed99e15>:0)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
