### ISSUE TITLE
[v1] The button is not pressed. Did I forget to add a component?

### ISSUE THREAD

**Issue by Scheshi** [mob-sakai/SoftMaskForUGUI#123]
The button does not work if the parent of the object has a Soft Mask. With a regular Mask it works great.

https://user-images.githubusercontent.com/47576867/117280754-96393f80-ae6b-11eb-8233-03618ebbdf8a.mp4

**Comment by SilkyPantsDan** [comment]
I was experiencing this issue as well @Scheshi - it seems there is an option on the Soft Maskable that needs to be enabled for the ray cast to hit correctly

<img width="517" alt="image" src="https://user-images.githubusercontent.com/738172/150890729-90c4912c-6b45-4899-9bda-77ac92d9ec4c.png">

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
