### ISSUE TITLE
[v1] Masked image affected by another object's mask

### ISSUE THREAD

**Issue by swoy45** [mob-sakai/SoftMaskForUGUI#125]
**Describe the bug**
When i'm using masked viewport with several children which are same-level in hierarchy and each of them has a soft mask they will use same-level mask buffer. Most of the time it wouldn't be noticeable because objects don't touching each other but when some of them need to be moved their masks could collapse and affect masked sprites of each other. So the option to isolate buffer layers could solve this problem.

**To Reproduce**
1. Create parent container with soft mask.
2. Create children with soft masked sprites inside each of them.
3. Move children close to each other so masked sprites affected by another object's mask.

**Expected behavior**
Ability to control layers in mask buffer.

**Screenshots**
![image](https://user-images.githubusercontent.com/17198492/120902897-92a3fe80-c64b-11eb-8568-b7a9ea243cbc.png)
![image](https://user-images.githubusercontent.com/17198492/120902983-09d99280-c64c-11eb-8f6a-56437422e3e9.png)

**Environment (please complete the following information):**
 - Version 1.0.0
 - Platform: Windows 10
 - Unity version: 2019.2.14f1

**Comment by marcelopapelgames** [comment]
Same issue with me.

The parent circle SoftMask is affecting the parent image (yellow bar), allowing it to show the child image (owl). 

The yellow bar covers completely the bottom part of the owl:
![Pasted Graphic 1](https://user-images.githubusercontent.com/81409029/213811603-cf497c40-2653-48c4-b3f7-b5399fdc9c5c.png)


With the SoftMask, part of the yellow bar is made transparent, showing parts of the owl :
![image](https://user-images.githubusercontent.com/81409029/213811524-4737227e-bc05-4ed4-8d7b-1c896ed8fe09.png)

**Comment by raaan127** [comment]
Hi, I'm also experiencing this bug while trying to use multiple nested softmask, I'm using 1.0.2 
![ảnh](https://github.com/mob-sakai/SoftMaskForUGUI/assets/67598197/b7b5e8d5-36bc-49f8-b096-94fa8ebd8363)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
