### ISSUE TITLE
[v1] Runtime generated graphics (like textmeshpro submesh) aren't softmaskable

### ISSUE THREAD

**Issue by pajama** [mob-sakai/SoftMaskForUGUI#126]
When textmeshpro fonts are bolded they generate a child graphic of type TMP_SubMeshUI. These objects are regenerated on play, so softmaskable components need to be added to them procedurally, which is expensive. 

But also when the softmaskable is added to them at runtime, the text goes completely invisible. Disabling the added softmaskable makes them visible again, but whenever it is enabled, the text disappears.

I should also note that when I switch it to "Visible Outside Mask" it ends up being visible inside the mask. So there must be something strange going on with the world position calculation.

 - SoftMaskForUGUI 1.0.0
 - Unity 2020.3.14f1
 - TextMeshPro 3.0.6

**Comment by pajama** [comment]
Also a note on the submesh from textmeshpro. It seems it's only ever generated if a font weight is selected where a replacement font is assigned. 
![image](https://user-images.githubusercontent.com/2224105/132549845-24339bb4-d044-49bc-8ab3-502bad875857.png)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
