### ISSUE TITLE
Shader error for TMPro

### ISSUE THREAD

**Issue by Moddingdudes** [mob-sakai/SoftMaskForUGUI#128]
After importing both TMPro essentials and the TMPro support, I am getting a shader error on Hidden/TextMeshPro/Mobile/Distance Field (SoftMaskable)

Error: "failed to open source file: 'Assets/TextMesh Pro/Resources/Shaders/TMPro_Properties.cginc'
Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR"

I looked around to try and find a solution and couldn't find anything. Any help would be appreciated!

**Comment by m1keall1son** [comment]
This is because TMP no longer keeps their shaders at Assets/TextMesh Pro/Resources/Shaders/TMPro_Properties.cginc

work around is to change it to Assets/TextMesh Pro/Shaders/TMPro_Properties.cginc and it will compile but this should be updated

**Comment by schichko** [comment]
Changing the above fixed it for me. References in the following files must be changed

TMP_SDF (SoftMaskable).shader
TMP_SDF-Mobile (SoftMaskable).shader

**Comment by mob-sakai** [comment]
Sorry for my late reply.
It has be released in [v1.0.2](https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/1.0.2).

Thanks to all of you for your cooperation! 👍
