### ISSUE TITLE
[v1] TMP only rendering in one eye on VR on SPI rendering path

### ISSUE THREAD

**Issue by m1keall1son** [mob-sakai/SoftMaskForUGUI#130]
Import TMP + essentials + XR Pluging management
Change to Single Pass Instanced Rendering 
See that TMP is only rendering in one eye (left eye)

**Comment by colonisationgames** [comment]
Also had this same issue

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
