### ISSUE TITLE
[v1] SoftMaskable Shader Not Included in Builds

### ISSUE THREAD

**Issue by nindim** [mob-sakai/SoftMaskForUGUI#132]
I've figured out that I need to add any custom SoftMaskable shaders to the "Always Included Shaders" list in Project Settings->Graphics (due to the use of Shader.Find in the source code). I think it would be good to get this added to the documentation to save future people like myself a little time :)

**Comment by PeraSite** [comment]
OMG I just figured out that shaders are missing on builds.
Thank you :)

**Comment by dariusjulian** [comment]
Did this ever get fixed?  I'm having the same issue.

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
