### ISSUE TITLE
[v1] Artefacts on iOS

### ISSUE THREAD

**Issue by gimmemypass** [mob-sakai/SoftMaskForUGUI#133]
**Describe the bug**
On iOS platform soft mask component create artefacts on sprites. Screenshots are attached

**To Reproduce**
1. Go to SoftMask component
2. Set Softness to 1
4. See artefacts on image
<img width="341" alt="Screenshot 2022-01-19 at 11 34 24" src="https://user-images.githubusercontent.com/49441827/150094615-2fb2fac6-c914-487c-97f1-9458855847ff.png">

**To Solve Bug**
1. Set Softness to 0.99
2. See no artefacts
<img width="338" alt="Screenshot 2022-01-19 at 11 34 33" src="https://user-images.githubusercontent.com/49441827/150094631-8b9b5de8-083e-46fb-8f0b-f31a0cac390c.png">

**Environment :**
 - Version 1.0.0
 - Platform: Editor Mac, iOS
 - Unity version: 2020.3.24f
 - Build options: IL2CPP, Net 4.x, Linear

**Comment by dcosmin-97** [comment]
Hello guys! Really nice asset!

I also have problems on iOS.

Version 1.0.0
Platform: Editor Mac, iOS
Unity Version - 2020.3.32f1
Build options: IL2CPP, Net 4.x

I am unable to fix the issue with softness at 0.99. The purple images are present in all the situations.
I am not able to fix the issue.

Thank you!

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
