### ISSUE TITLE
[v1] If the Canvas size is not the same as the screen size, the mask position will be incorrect，like on ipad.

### ISSUE THREAD

**Issue by xuxy01** [mob-sakai/SoftMaskForUGUI#137]
it seems like that the uv of _SoftMaskText is Incorrect。

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
