### ISSUE TITLE
[v1] Use only alpha value to control transparency of regular rectangular mask

### ISSUE THREAD

**Issue by fmatulic** [mob-sakai/SoftMaskForUGUI#138]
I have an image as sole child of a regular rectangular mask and I just want to control the level of transparency of the whole image/mask. Is this possible with SoftMaskForUGUI? When I converted my Unity mask to Soft Mask my image turned all white and I wasn't able to get it to appear by fiddling with the options exposed in the inspector.

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
