### ISSUE TITLE
[v1] Adding a parent SoftMask would cause raycast filter not work correctly on overlapping SoftMaskables

### ISSUE THREAD

**Issue by SaturnusK1** [mob-sakai/SoftMaskForUGUI#139]
**Describe the bug**
I was facing the issue reported in #109 and tried to fix it by adding the parent SoftMask but it caused the Raycast Filter on overlapping SoftMaskables not work correctly.

**To Reproduce**
I attached a sample project to explain the repro steps. You can read the extended explanation the ReadMe file in Assets folder of the project.
Basically the masked roof look like the second screenshot but the raycast area is the same as the third one.

**Expected behavior**
The raycast filter shape should be the same as the masked shape

**Screenshots**
![image](https://user-images.githubusercontent.com/19710519/184107687-7a968e27-39be-43d6-8baa-6a5a889cb5d7.png)
![image](https://user-images.githubusercontent.com/19710519/184107713-f2b29ed2-7ae5-4759-9419-16c3b12a55ed.png)
![image](https://user-images.githubusercontent.com/19710519/184107730-eed1821f-b0f4-47b5-83a5-41a24ac4cd37.png)

**Environment (please complete the following information):**
 - Version [1.0.0]
 - Platform: [Editor(Windows)]
 - Unity version: [2019.4.11f1]

[SoftMaskSample.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/9307728/SoftMaskSample.zip)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
