### ISSUE TITLE
Mask preview in Prefab Mode

### ISSUE THREAD

**Issue by Yerendi-hub** [mob-sakai/SoftMaskForUGUI#140]
As in title - is it possible to add preview on scene view in prefab mode? Currently I can only see my mask graphic, soft mask buffer is full red, masked graphic is not visible. When I do it directly on scene (not in prefab mode) evrything is working fine.

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by Zony-Zhao** [comment]
I just installed the lib, and did as the usage part of Readme file. I found my mask not working. Then I turn to the issues of repo, and this issue reminds me that it's not working in prefab mode. This is a little confusing though. 
I think in most propject of a decent size, developers edit thier UI in a prefab mode and then test in the scene. If it is a troublesome feature to implement, u should mention it in the readme 'usage' part, letting users know what's going on.
By the way, great work!

**Comment by oddoscar** [comment]
Side note: SoftMask works for me in 2022.3 in Prefab Mode, as long as the UI element in question in inside the **screen frame**.

![image](https://github.com/mob-sakai/SoftMaskForUGUI/assets/97726126/d2762561-6ba8-4085-84bb-b4089d85997e)
_SoftMask works inside the screen frame, in Prefab Mode._

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
