### ISSUE TITLE
2021.1.0a12

### ISSUE THREAD

**Issue by XeonG** [mob-sakai/SoftMaskForUGUI#141]
NullReferenceException: Object reference not set to an instance of an object
Coffee.UISoftMask.SoftMask.UpdateMaskTextures () (at Assets/Kraftzone.net/ThirdParty/SoftMaskForUGUI-main/Scripts/SoftMask.cs:476)
UnityEngine.Canvas.SendWillRenderCanvases () (at <f42a35824f1a4d1eac5c8c540bcb9b28>:0)

**Comment by mob-sakai** [comment]
Sorry for my late reply.
The GameObject does not have `Graphic` component such as `Image`, `RawImage`.
