### ISSUE TITLE
[v1] "Part of parent" option is unreliable

### ISSUE THREAD

**Issue by tomkail** [mob-sakai/SoftMaskForUGUI#144]
**Describe the bug**
Trying to create a composite mask with children is glitchy and doesn't work reliably.

**To Reproduce**
Just try to create a composite mask and add some maskables! Sometimes the soft mask preview appears empty. Other times, what's shown in the scene view differs from game view. Pressing save can often cause what's shown to change.

**Expected behavior**
Consistent masking.

**Environment (please complete the following information):**
 - Version 1.0.2
 - Platform: Editor, OSX (Metal)
 - Unity version: [e.g. 2021.3.5f1]

**Additional context**
Have encountered this in various projects.

**Comment by mob-sakai** [comment]
Sorry for my late reply.
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
