### ISSUE TITLE
[v1] Specifying a maskable in the inspector outside the mask

### ISSUE THREAD

**Issue by SnoupS** [mob-sakai/SoftMaskForUGUI#146]
Please make it possible to specify a global maskable for all masks or specify a maskable in the mask outside of it.

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
