### ISSUE TITLE
Error when importing this asset + SoftMaskable not working

### ISSUE THREAD

**Issue by APTEM591** [mob-sakai/SoftMaskForUGUI#148]
**Describe the bug**
I have imported this asset to my project but it returns me an error: 

> Shader error in 'Hidden/UI/Default (SoftMaskable)': Couldn't open include file 'Packages/com.coffee.softmask-for-ugui/Shaders/SoftMask.cginc'. at line 58
>
> Compiling Subshader: 0, Pass: Default, Vertex program with SOFTMASK_EDITOR
> Platform defines: SHADER_API_MOBILE UNITY_COLORSPACE_GAMMA UNITY_ENABLE_REFLECTION_BUFFERS UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_NO_CUBEMAP_ARRAY UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2
> Disabled keywords: SHADER_API_GLES30 UNITY_ASTC_NORMALMAP_ENCODING UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHTMAP_RGBM_ENCODING UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_FULL_STANDARD_SHADER UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_UI_ALPHACLIP UNITY_UI_CLIP_RECT UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_VIRTUAL_TEXTURING

**Screenshots**
![image](https://user-images.githubusercontent.com/71151134/215154726-16f93a7a-2ace-4f8a-85b6-8e79e3bfdaeb.png)

**Environment (please complete the following information):**
 - Version 1.0.2
 - Platform: Editor(Windows)
 - Unity version: 2021.3.14f1
 - Build options: IL2CPP

**Comment by APTEM591** [comment]
Wrong installation. My bad.

**Comment by niechaiev** [comment]
@APTEM591 
I have the same problem when doing Embedded Package setup. I don't understand your "Wrong installation" comment. 
It is literally one step to move src folder, but I have tried 3 different versions of this asset + Unity 6 and 2022, and still get the same error every time. 
Please elaborate

**Comment by APTEM591** [comment]
> [@APTEM591](https://github.com/APTEM591) I have the same problem when doing Embedded Package setup. I don't understand your "Wrong installation" comment. It is literally one step to move src folder, but I have tried 3 different versions of this asset + Unity 6 and 2022, and still get the same error every time. Please elaborate

I don't remember exactly because it was 2 years ago, but now, as I see, I have it installed from UPM, not with unitypackage, maybe this was the problem.
