### ISSUE TITLE
Can't use Text Mesh Pro UGUI Text as a SoftMask

### ISSUE THREAD

**Issue by nindim** [mob-sakai/SoftMaskForUGUI#149]
Hi,

When adding a SoftMask component to a game object that has an existing TextMeshPro - Text (UI), it does not soft mask child objects with the SoftMaskable component.

When previewing the Soft Mask Buffer, it is just black.

Basic masking does kind of work if "Use Stencil" is ticked and you invert the "Mask Interaction", but then it loses the softness...

**Environment (please complete the following information):**
 - Version: 1.0.2
 - Platform: Editor(Windows)
 - Unity version: 2021.3.17
 - Build options: N/A

![image](https://user-images.githubusercontent.com/7597004/219699909-843a9b77-d958-4fe3-890c-d4fd23fedc35.png)
![image](https://user-images.githubusercontent.com/7597004/219699968-a1b10792-3e6c-49ee-8d94-03ff4917f757.png)
![image](https://user-images.githubusercontent.com/7597004/219700029-41eecb7e-1723-4b4e-800a-bdd389b4b80e.png)

Does anyone know how to fix this or add support?

Thank you,

Niall

**Comment by mob-sakai** [comment]
Sorry for my late reply.
In v1.0.2, TextMeshProUGUI cannot be used as a masking graphic. This will be supported in v2.
