### ISSUE TITLE
How to use the inverted mask?

### ISSUE THREAD

**Issue by alexanderameye** [mob-sakai/SoftMaskForUGUI#152]
I would like to use an inverted cutout mask just like this package (just like the iris sample)
https://github.com/mob-sakai/UnmaskForUGUI

But it is unclear to me how I can achieve the same effect using this soft mask package?

Thanks

**Comment by f1yingbanana** [comment]
On the `SoftMaskable` component, untick use stencil and change interaction mode to visible outside mask.

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
