### ISSUE TITLE
[v1] Soft mask doesn't work, Unity 2020.3.33f1

### ISSUE THREAD

**Issue by PJblue** [mob-sakai/SoftMaskForUGUI#153]
**Describe the bug**
Masked sprite does not appear when using soft mask.

**To Reproduce**
1. Add soft mask via UPM from https://github.com/mob-sakai/SoftMaskForUGUI.git
2. Add sample scene via UPM
3. Look at examples. Masked text appears, but masked sprite does not.
4. Create your own masked sprite setup, same behavior.

**Comment by mob-sakai** [comment]
Sorry for my late reply.
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
