### ISSUE TITLE
ParticleAttractor support for List of Particles and allow them to be attached and detached at runtime

### ISSUE THREAD

**Issue by YanickFrehner** [mob-sakai/SoftMaskForUGUI#154]
**Is your feature request related to a problem? Please describe.**
I want to have an Attractor and then Instantiate Particle System at runtime and attach them to the attractor

**Describe the solution you'd like**
What i have in mind is a public Detach and Attach function with the ParticleAttractor and then make the particle function work with a list of particle System which all are being attracted by the same ParticleAttractor

**Comment by mob-sakai** [comment]
ParticleAttractor is not used in this project.
