### ISSUE TITLE
Unable to get Soft Mask to work - console fills with errors

### ISSUE THREAD

**Issue by Gekkosaurus-Dev** [mob-sakai/SoftMaskForUGUI#155]
**Describe the bug**
Not able to use the soft mask. I get errors and cannot get it to work.
Looks like there is another thread related to the soft mask not working in unity version 2020? Could this be related?

**To Reproduce**
1. Use Unity Package Manager to add SoftMaskForUGUI via https://github.com/mob-sakai/SoftMaskForUGUI.git
2. Add a 2d circle sprite to the scene
3. Add Soft Mask component
4. Immediately the console is full of this error: 
![image](https://user-images.githubusercontent.com/111717811/235303819-3ef625ee-8794-4648-bdd4-5270669cebd2.png)

I do not know what other way that I should be adding the Soft Mask if this is incorrect?

**Environment:**
 - Version: 1.0.2
 - Platform:: Windows
 - Unity version: 2022.1.8f1

**Comment by RunoLight** [comment]
Look into readme, there should be at least 2 objects, where parent has softmask and child has softmaskable components

**Comment by mob-sakai** [comment]
Sorry for my late reply.
This package provides a soft mask for UI. SpriteRenderer is not supported.
