### ISSUE TITLE
[v1] Masked UI image vanishes when dragged

### ISSUE THREAD

**Issue by mrchooch** [mob-sakai/SoftMaskForUGUI#156]
I'm using this mask on a UI image that can be dragged around the screen. However, when it's dragged, whatever image is a child of the mask simply disappears

**Comment by mob-sakai** [comment]
Sorry for my late reply.
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
