### ISSUE TITLE
[v1] I can't make a material for the Image based on the Default SoftMaskable shader

### ISSUE THREAD

**Issue by Wiggan** [mob-sakai/SoftMaskForUGUI#158]
**Describe what help do you need**
I'm trying to make a material with some input parameters that should also be soft maskable.
I've both tried making a material based on the default UI SoftMaskable shader and copying the whole shader and followed the naming convention described here: https://github.com/mob-sakai/SoftMaskForUGUI#support-soft-masks-with-your-custom-shaders. As soon as this material is used in context (on an image with softmaskable component that is child of a SoftMask Image) the shader of the maskable image turns into Hidden/InteralErrorShader. This only happens when in the context described. 

Version of SoftMask is 1.0.2
We use URP, Unity 2022.3.7f1.

**Comment by mob-sakai** [comment]
Sorry for my late reply.
Please check for shader compilation errors.

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
