### ISSUE TITLE
[v1] When creating AssetBundle and loading them into an Android application, SoftMaskUI does not work.

### ISSUE THREAD

**Issue by shaddyarm** [mob-sakai/SoftMaskForUGUI#159]
Hello! I have encountered a problem that I can't solve in any way. The thing is that I download covers from the server as AssetBundles and import them into the game. SoftMaskUI attached to the covers and when loading into the game via Unity everything works fine, but when loading on Android, SoftMaskUI seems to disappear. I've already tried adding SoftMaskUI to the default shaders, but unfortunately that didn't help. I would be immensely grateful if you could help me solve this problem!
![Untitled-2](https://github.com/mob-sakai/SoftMaskForUGUI/assets/66546517/8f4070f0-967e-41b2-94ab-ad8316f4a114)

**Comment by tomaszheng** [comment]
I had the same problem

**Comment by ndumais** [comment]
I have the same issue, I could be wrong but I think it currently does not support Mobile?

Editor
![image](https://github.com/mob-sakai/SoftMaskForUGUI/assets/48096495/ee849798-a4ab-48ba-a748-164f018745bd)

Android Build
![image](https://github.com/mob-sakai/SoftMaskForUGUI/assets/48096495/55cfd397-b6d2-4dc0-bd30-d9003101bc75)

**Comment by mob-sakai** [comment]
Sorry for my late reply.
I would like to know more about this issue.
Tell me about your develop/build environment.
 - 〇〇 version [e.g. 3.3.10]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2022.2.0f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP/HDRP]

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
