### ISSUE TITLE
SoftMaskForUGUI v2

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/SoftMaskForUGUI#162]
# Key Features

- Add project settings for UISoftMask.
- Add assets modification system to upgrade V1 to V2.
- Improve the shaders:
  - Add stereo mode.
  - Exclude unused shader variants from the build.
- Add `AntiAliasing` masking mode.
  - This mode suppresses stencil-derived mask aliasing without using RenderTexture.
- Add `SoftMask.softnessRange` option:
  - It contains 2 values (min/max)
  - `SoftMask.softness` is obsolete.
- Add `MaskingShape` component:
  - To add/remove masking area.
  - `SoftMask.partOfParent` will be obsolete.
- Add support for UI components:
  - TexMeshPro SubMeshUI
  - ~[UIParticle](https://github.com/mob-sakai/ParticleEffectForUGUI)~ ommited
  - ~[CompositeCanvasRenderer](https://github.com/mob-sakai/CompositeCanvasRenderer)~ ommited
- `SoftMaskable` component will be auto-generated object.
  - The options such as `SoftMaskable.maskInteraction` will be removed.
- Fix rendering issues on certain devices.

**Comment by tpnet** [comment]
Looking forward to it very much. May I ask when the author will update

**Comment by afshinunity** [comment]
very nice, keep going. it must be a unity built-in feature.

**Comment by tpnet** [comment]
May I ask when it will be released in the official version～please

**Comment by mob-sakai** [comment]
Sorry for my late reply.
It will likely be released this week! If you want to try it out, install the package as follows:

```json
"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src#develop-preview"
```

Alternatively, download the code and place `Packages/src` directory into the `Packages` in your project.
https://github.com/mob-sakai/SoftMaskForUGUI/archive/refs/heads/develop-preview.zip

**Comment by mob-sakai** [comment]
Released
