### ISSUE TITLE
[v1] Using this soft mask with text mesh pro in unity 2023 makes the text blocky like the shader dosen't work

### ISSUE THREAD

**Issue by TheEye2108** [mob-sakai/SoftMaskForUGUI#163]
As the title seas it seems to not work properly or did i miss a step i just imported the extra text mesh pro assets? Any help is appreciated.

**Comment by AgainJBC** [comment]
Seems to happen for >TextMeshPro/Distance Field< sharder ....  >TextMeshPro/Mobile/Distance Field< seems working fine

**Comment by karyol** [comment]
I managed to fix it by copying the default Distance Field shader from TMP and making minor adjustments.
First changed the shader name to `Hidden/TextMeshPro/Distance Field (SoftMaskable)`.
Second change is in `Pass`. Edit pragmas and includes like this:
```				
#pragma target 3.0
#pragma vertex VertShader
#pragma fragment PixShader
#pragma shader_feature __ BEVEL_ON
#pragma shader_feature __ UNDERLAY_ON UNDERLAY_INNER
#pragma shader_feature __ GLOW_ON

#pragma multi_compile __ UNITY_UI_CLIP_RECT
#pragma multi_compile __ UNITY_UI_ALPHACLIP

#include "UnityCG.cginc"
#include "UnityUI.cginc"
#if UNITY_VERSION < 201910
  #include "Assets/TextMesh Pro/Resources/Shaders/TMPro_Properties.cginc"
  #include "Assets/TextMesh Pro/Resources/Shaders/TMPro.cginc"
#else
  #include "Assets/TextMesh Pro/Shaders/TMPro_Properties.cginc"
  #include "Assets/TextMesh Pro/Shaders/TMPro.cginc"
#endif

#include "Packages/com.coffee.softmask-for-ugui/Shaders/SoftMask.cginc"
#pragma shader_feature __ SOFTMASK_EDITOR
```
With softmask editor included you can add softmask to your text but you need to know the world position and there comes the third change.
Add `float4 worldPosition : TEXCOORD6;` to `struct pixel_t`.
Then you need to add world position from input to output `output.worldPosition = input.position;` in `VertShader` just before returning the output.
And finally you can add the softmask into `PixShader`  just before returning `faceColor` `faceColor *= SoftMask(input.position, input.worldPosition);`.
It works for soft masking the TMPro texts for me but i still do not managed to make it work for TMP inline sprites.

**Comment by TheEye2108** [comment]
I managed to make it work with unities built in soft mask but then we had to downgrade to unity 2022 and there we had other problems so we just scraped the soft mask part and just went with the hard mask ore just mask :D.
But ty for posting this i will try and implement it for testing.

**Comment by SeanNi1221** [comment]
Make sure the TextMeshPro Support package is imported into your Asset folder as stated in
https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#usage-with-textmeshpro
I think the author @mob-sakai maded it a bit misleading putting the resources under a folder called "Samples".

**Comment by akpil** [comment]
> Make sure the TextMeshPro Support package is imported into your Asset folder as stated in https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#usage-with-textmeshpro I think the author @mob-sakai maded it a bit misleading putting the resources under a folder called "Samples".

I am experiencing the same issue as described in this thread, and I have definitely installed the package you mentioned. (If it isn't installed, it appears in magenta.) However, even after installation, the color that was magenta just shows up as a black (or the color of the font) rectangle. In the 2023 version, the same issue occurs no matter how I bake the font asset, whereas in version 2022.3.x, everything works perfectly with the same settings. Therefore, the method you suggested does not solve the problem.

**Comment by mob-sakai** [comment]
Sorry for my late reply.

The TextMeshPro shader does not work correctly in the following environments due to updates:

- Unity 2023.2 and Unity 6 (TextMeshPro is built into uGUI)
- TextMeshPro v3.2.0-pre and v4.0.0-pre

As a workaround, please try the following:

- If you have already imported the TextMeshPro Support sample, delete the folder.
- Extract the following zip file into the Assets folder:
   - [TextMeshPro Support v3.2 or v4.0.zip](https://github.com/user-attachments/files/15538172/TextMeshPro.Support.v3.2.or.v4.0.zip)
- Add the shaders to `Project Settings > Shader Settings > Always Included Shaders`  
   ![](https://github.com/mob-sakai/SoftMaskForUGUI/assets/12690315/7736f118-8d97-41f8-a3d1-b03624ba0271)


![](https://github.com/mob-sakai/SoftMaskForUGUI/assets/12690315/2ed05472-8967-4822-8268-0533eee0c800)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
