### ISSUE TITLE
[v1] Non-maskable TMPro text masks until "Maskable" re-disabled

### ISSUE THREAD

**Issue by APTEM591** [mob-sakai/SoftMaskForUGUI#164]
**Describe the bug**
Text is not visible even with Maskable disabled

**To Reproduce**
1. Instantiate prefab under SoftMask
2. Set this object active (which is child of another object in my situation)
3. Background image is visible outside the mask, text is not.

**Expected behavior**
Text won't be masked outside the mask, same as background.

**Environment (please complete the following information):**
 - Version 1.0.2
 - Platform: Windows Editor, Android platform
 - Unity version: 2022.3.10f1
 - Build options: doesn't matter, bug in the editor

**Additional context**
It fixes if I enable Maskable and disable it, only in the inspector, doesn't work from code.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
