### ISSUE TITLE
[v1] Masked elements are off-set if canvas is not full screen

### ISSUE THREAD

**Issue by alberto-salieto-scopely** [mob-sakai/SoftMaskForUGUI#165]
Hello,

**Description**
Masked elements are off-set if canvas is not full screen.

It is caused by line 39 in `SoftMask.cginc`

`half2 view = clipPos.xy/_ScreenParams.xy;`

specifically `_ScreenParams.xy`. According to https://docs.unity3d.com/Manual/SL-UnityShaderVariables.html, it returns camera render size in pixels, not canvas size. Proposed fix is to pass offsets to calculate true canvas size and position.

**Expected behavior**
The mask should be in the proper position according to the canvas position. In our case, canvas is displaced because of the notch, so it doesn't have the fullscreen size.

**Environment**
 - Version 1.0.2 - May 15, 2022
 - Platform: Editor (Windows/Mac), Standalone(Windows/Mac), iOS, Android
 - Unity version: 2021.3.36f1

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
