### ISSUE TITLE
[v1] I tried changing properties of material using softmaskable but the gameobject properties stay the same

### ISSUE THREAD

**Issue by raaan127** [mob-sakai/SoftMaskForUGUI#166]
I tried to change property of a material that attached into Image component
I tried on runtime and nothing happen so I change the property on editmode, the original material's properties is changed but the softmaskable material property stay the same.

![ảnh](https://github.com/mob-sakai/SoftMaskForUGUI/assets/67598197/23d76095-f2e6-4844-a5df-fbf452061686)
![ảnh](https://github.com/mob-sakai/SoftMaskForUGUI/assets/67598197/d5c89385-2254-41de-8fa3-12c63980fc22)

**Comment by mob-sakai** [comment]
Thank you for your reporting!

This behavior is a specification of the instantiated material and will be reproduced in `Mask` as well as `SoftMask`.
If `RawImageTilingOffset` component directly modifies the material parameters of `graphic.material`, the changes will not be reflected in the instantiated material.

As a workaround, `RawImageTilingOffset` component needs to implement the following.

1. Implement `IMaterialModifier` interface. `GetModifiedMaterial` method as follows:
   - Create a new material instance from the baseMaterial. Cache the material instance to avoid unnecessary creation.
   - Use `material.Set***` method to modify the parameters of the instantiated material.
   - Try to keep the implementation of the `GetModifiedMaterial` method as low load as possible.
2. Call `graphic.SetMaterialDirty` method when `Scale` or `OffsetSpeed` is changed, or in `OnValidate` method.

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
