### ISSUE TITLE
[v1] TMP Texture breaks when Softmask applied, Unity 2022.3, URP, iOS target

### ISSUE THREAD

**Issue by josh-ruthnick** [mob-sakai/SoftMaskForUGUI#169]
**Describe the bug**
TMP is not supported once I apply the "Soft Maskable Script". All textures break and turn pink.  

**To Reproduce**
1. Add a UI Image and apply mask
2. Add a child TMP object
3. Convert Mask to Softmask
4. Press "Fix" to apply "soft maskable script" to children objects
5. TMPs turn pink with broken texture

**Expected behavior**
TMP masks correctly

**Screenshots**
<img width="1525" alt="mask1" src="https://github.com/mob-sakai/SoftMaskForUGUI/assets/142555235/a0561d89-347c-4f56-b5c3-5e6e6b5cfba5">
<img width="1628" alt="mask2" src="https://github.com/mob-sakai/SoftMaskForUGUI/assets/142555235/cf6da23a-cfa9-473c-98c5-041c5e00b077">

**Environment (please complete the following information):**
 - Platform: iOS, URP
 - Unity version: 2022.3.10f1

**Comment by mob-sakai** [comment]
Please try v2: https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/v2.0.0

- [⚙ Installation](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-installation)
