### ISSUE TITLE
When building with Vulkan and Landscape Orientation, SoftMask does not work on the device.

### ISSUE THREAD

**Issue by Yunday-dev** [mob-sakai/SoftMaskForUGUI#171]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
When building with Vulkan and OpenGLES3 in that order as Graphics APIs and Landscape orientation, SoftMask does not work.
However, It works correctly in the Editor and on the device in Portrait orientation.

[It works correctly on the Editor]
![image](https://github.com/user-attachments/assets/54038c0b-c753-449c-b7c7-f27f81d701f5)

[It works correctly in Device with Portrait orientation]
![Protrait](https://github.com/user-attachments/assets/57a3fa47-ee85-4c1e-9a91-0a63d5f63e41)

[It does not works in Device with Landscape orientation]
![Landscape](https://github.com/user-attachments/assets/b93121fa-bf74-4ac4-b14d-8237d758f273)

However, SoftMask works correctly when building with OpenGLES3 and Vulkan in that order.
![ProtraitCorrectly](https://github.com/user-attachments/assets/06fabaa1-43d2-4e7c-bf63-11390462f416)

**To Reproduce**
I build with Vulkan and OpenGLES3 in that order, as shown in the image below.
<img width="280" alt="image" src="https://github.com/user-attachments/assets/32094776-45f0-4374-9ae0-df921da70d3c">

And I set the Orientation to Landscape.
![image](https://github.com/user-attachments/assets/7065e4b4-3918-4989-8f53-3951e447a1a5)

I build.

**Expected behavior**
SoftMask should work correctly on the device even when building with Vulkan and setting the Orientation to Landscape.

**Screenshots**
It works correctly in Portrait orientation but does not work correctly in Landscape orientation.
![trainsition_portrait_to_landscape](https://github.com/user-attachments/assets/c4008359-d1af-4802-8342-af3ab3d6da54)

**Environment (please complete the following information):**
 - Version: 2.0.0
 - Platform: Editor(Windows), Android
 - Unity version: 2022.3.21f1
 - Build options: Vulkan, IL2CPP, .Net Standard 2.1, URP

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
The issue is reproduced when building with the following settings:

- Unity 2022.3.18f1, Android
- For `Graphics APIs`, prioritize `Valkan`
  ![](https://github.com/user-attachments/assets/f6d21bbe-752c-4ba5-9601-36a2024c9635)
- Enable `Valkan Settings > Apply display rotation during rendering`
  ![](https://github.com/user-attachments/assets/e630ab0b-6cd4-4df8-b191-9a42d7136a0c)

@Yunday-dev 
If 'Valkan Settings > Apply display rotation during rendering' is disabled, does it fix the problem?

**Comment by mob-sakai** [comment]
I have found the page I need.
https://docs.unity3d.com/Manual/vulkan-swapchain-pre-rotation.html

![](https://github.com/user-attachments/assets/988ec294-f7b5-4ceb-8e4a-a2e27de14120)

**Comment by Yunday-dev** [comment]
> The issue is reproduced when building with the following settings:
> 
> * Unity 2022.3.18f1, Android
> * For `Graphics APIs`, prioritize `Valkan`
>   ![](https://private-user-images.githubusercontent.com/12690315/350256390-f6d21bbe-752c-4ba5-9601-36a2024c9635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MDg1MzUsIm5iZiI6MTcyMTYwODIzNSwicGF0aCI6Ii8xMjY5MDMxNS8zNTAyNTYzOTAtZjZkMjFiYmUtNzUyYy00YmE1LTk2MDEtMzZhMjAyNGM5NjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAwMzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNmQ1MDU4YWRiZmE2OTQwZWZkYmQ4MDk0ZTVmMDI3Y2NjMGRiNThhNDRiMjljZjM3OGFiYmVmNWU5YjM1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gh1z39ne-RlRKiRTrnEoZANz-gPH96LMMTQ_y-IDfuQ)
> * Enable `Valkan Settings > Apply display rotation during rendering`
>   ![](https://private-user-images.githubusercontent.com/12690315/350255278-e630ab0b-6cd4-4df8-b191-9a42d7136a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MDg1MzUsIm5iZiI6MTcyMTYwODIzNSwicGF0aCI6Ii8xMjY5MDMxNS8zNTAyNTUyNzgtZTYzMGFiMGItNmNkNC00ZGY4LWIxOTEtOWE0MmQ3MTM2YTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAwMzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NGQzODE3M2E3ZjFlY2Y4ZjhjNzdlOTg2NjEwNmJkNjZhMjQyZGFhYWRlMWRkOTRhYWY4OWVhNWNhNzA3YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_GYaOULqAxi2TTGZveqwc0KmODIRlVx_v9Kc2ClU80)
> 
> @Yunday-dev If `Valkan Settings > Apply display rotation during rendering` is disabled, does it fix the problem?

Disabling 'Vulkan Settings > Apply display rotation during rendering' prevents the issue.

**Comment by Yunday-dev** [comment]
> I have found the page I need. https://docs.unity3d.com/Manual/vulkan-swapchain-pre-rotation.html
> 
> ![](https://private-user-images.githubusercontent.com/12690315/350330692-988ec294-f7b5-4ceb-8e4a-a2e27de14120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MDkyOTQsIm5iZiI6MTcyMTYwODk5NCwicGF0aCI6Ii8xMjY5MDMxNS8zNTAzMzA2OTItOTg4ZWMyOTQtZjdiNS00Y2ViLThlNGEtYTJlMjdkZTE0MTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAwNDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZDE5MDVhMzUwZTZlYjM4NWQ3ZjdhYjc4NzU4ODkzY2E0MzExYTY0Zjc4ZTM3NjYzMGM0NjRlZjJhMWVmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W6aPCG8TFf8lHqlVFo9msb4u3e8mFItLS-9PtkIWwQc)

It works! Thank you very much.
