### ISSUE TITLE
Text Mesh Pro UGUI Text Displays Abnormally Under SoftMask 2.0.0

### ISSUE THREAD

**Issue by buger404** [mob-sakai/SoftMaskForUGUI#173]
**Describe the bug**
I am using SoftMask version 2.0.0. As shown in Figure 1, it details the settings of the Text and its normal appearance. When I add SoftMask to its parent object, as shown in Figure 2, it becomes blurry and turns black.

**To Reproduce**
1. Add an Image and set its color to argb(1,255,255,255)
2. Add a TMP Text inside the Image
3. Add SoftMask to the Image

**Screenshots**
* Figure 1
![Figure 1](https://github.com/user-attachments/assets/d7c5bbc8-494d-4cdc-a413-6f1435718015)
* Figure 2
![Figure 2](https://github.com/user-attachments/assets/81d081a8-3804-42fa-b89d-ede84a4c4380)

**Environment (please complete the following information):**
 - Version 2.0.0
 - Platform: Windows Editor
 - Unity version: 2022.3.38f1
 - Text Mesh Pro version: 3.0.6
 - Build options: IL2CPP

**Comment by buger404** [comment]
Here is a blank project to reproduce this issue. I hope it helps:
[SoftMaskTest.zip](https://github.com/user-attachments/files/16319209/SoftMaskTest.zip)

**Comment by buger404** [comment]
Oh, I am very sorry. I upgraded from v1 to v2 without carefully reading the instructions regarding TextMeshPro support. I imported the corresponding sample and resolved the issue.

**Comment by buger404** [comment]
Hi, I discovered today that this issue occurred again when I compiled for the Android platform. There were no warnings or errors. The Graphics API settings are OpenGLES3 > Vulkan (Auto Graphics API is turned off).

**Comment by mob-sakai** [comment]
@buger404 What's up?

**Comment by buger404** [comment]
> @buger404 What's up?

Oh oh oh, I'm really sorry... I thought there was a new issue, but I just realized I forgot to include those shaders in the built-in shaders. Sorry for bothering you, I'll make sure to double-check next time before bringing up an issue.

**Comment by thanhtdln** [comment]
how exactly did you fix this btw?

**Comment by buger404** [comment]
> how exactly did you fix this btw?

you can have a try to import the sample, you can find that in the package manager.

**Comment by thanhtdln** [comment]
> you can have a try to import the sample, you can find that in the package manager.

Well actually i'm having the same problem with the latest version of SoftMask without even clicking on the "Upgrade" button in the settings in my own project. Do i just reimport the package or what else should i do?

**Comment by thanhtdln** [comment]
Ok somehow it's just because i was just dumb. I didnt even read the documents before trying to use the package so i did not import TextMeshPro support in the sample section. Sorry for that :D
