### ISSUE TITLE
Soft mask doesn't work on TextMeshPro when render mode is set to Raster

### ISSUE THREAD

**Issue by dsinkerii** [mob-sakai/SoftMaskForUGUI#174]
**Describe the bug**
Soft mask doesn't apply to TextMeshPro text when the render mode is set to Raster.

**To Reproduce**
1. Generate/Get a TMP font asset with render mode set to raster.
2. Create a mask object for that text.
3. Create an object TextMeshProUGUI with the font asset.

**Expected behavior**
Text being masked by the mask object.

**Actual behavior**
Text not being rendered at all

**Screenshots**
![image](https://github.com/user-attachments/assets/1905037a-0829-4c16-9728-255161ec71f0)
^ Mask image and text without the soft mask being enabled
![image](https://github.com/user-attachments/assets/d52b3f4a-4cda-4674-afb3-a748b06b3142)
^ Soft mask script enabled, with show mask graphic being set to true (when ticked off it is not being rendered at all)

**Environment (please complete the following information):**
 - v2.0.0
 - Platform: Windows, Mac, Linux OpenGL 4.5 (device on linux)
 - Unity version: 2022.3.9f1
 - Build options: URP

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by dsinkerii** [comment]
after a bit of time i realized i could've used the standard mask script mixed with soft mask, which works perfectly, so sorry for wasted time 😅
great project btw!
