### ISSUE TITLE
SoftMaskable Component cannot be removed.

### ISSUE THREAD

**Issue by ctw-daigo-sakamoto** [mob-sakai/SoftMaskForUGUI#175]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
SoftMaskable Component cannot be removed.

**Screenshots**
![sm](https://github.com/user-attachments/assets/549dee97-e61c-472c-be32-c510b03b5934)

**Environment (please complete the following information):**
 - Version 2.0.0
 - Platform: UnityEditor
 - Unity version: 2023.1.20f1
 - Build options: BuiltIn Shader And URP

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Reopen the scene or prefab and it should be deleted.
Or try [🔄 Upgrading from v1 to v2](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#-upgrading-from-v1-to-v2).

**Comment by mob-sakai** [comment]
@ctw-daigo-sakamoto 
Do you think we need an option to remove `HideFlags.NotEditable` or hide SoftMaskable?

**Comment by ctw-daigo-sakamoto** [comment]
When I reloaded the scene, it had been deleted.
Thank you for your answer.

>Do you think we need an option to remove HideFlags.NotEditable or hide SoftMaskable?

I think it would be helpful if there was an explanation in the Inspector for the SoftMaskable component,
by using EditorGUILayout.HelpBox(...).

**Comment by mob-sakai** [comment]
Ah, that's a good idea! 👍

**Comment by mob-sakai** [comment]
![](https://github.com/user-attachments/assets/17c99206-dda7-40ac-8095-6a35173748f1)
