### ISSUE TITLE
Masked elements randomly disappear (EDIT: not randomly, it occurs when create a object with TMP)

### ISSUE THREAD

**Issue by ryushinnn** [mob-sakai/SoftMaskForUGUI#180]
**Describe the bug**
Object A has SoftMask component, showMaskGraphic disabled. Objects B,C,D are children of A and they disappear randomly. If I enable showMaskGraphic and then disable it again, B,C,D are visible now. 

**To Reproduce**
It occurs randomly so I don't know how to reproduce it

**Expected behavior**
B,C,D are always visible

**Screenshots**
When the problem occurs:
![image](https://github.com/user-attachments/assets/7c4d3ef7-ce47-4d7a-8333-aec08d704754)

After I enable and disable showMaskGraphic (expected result):
![image](https://github.com/user-attachments/assets/d268ab40-59c7-49ba-b59c-de9be829756a)

**Environment (please complete the following information):**
 - Version: 2.1.3
 - Platform: Editor (windows)
 - Unity version: 2022.3.22f1
 - Build options: IL2CPP, .NET 4.x, built-in RP

**Comment by tienassassin** [comment]
update:

The problem occurs every time I create a new child of A and it has TMP component. Disable and enable SoftMask component of object A again also brings back B,C,D's visibility

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by cdanek** [comment]
I can add a repro process for this:

Create a SoftMask GO, nest a GO with an Image (sprite). Move the child object, then undo. The image disappears until an update of some kind is forced in SoftMask.

**Comment by mob-sakai** [comment]
The issue is reproduced on my environment.
I will fix it.

**Comment by mob-sakai** [comment]
@cdanek 

Thanks, it is reproduced on my environment.
I will fix it.

**Comment by mob-sakai** [comment]
@ryushinnn 
I would like to know more about this issue.

> The problem occurs every time I create a new child of A and it has TMP component. Disable and enable SoftMask component of object A again also brings back B,C,D's visibility

Does "A new child of A" has `SubMeshUI`?
In other words, does it use fallback material or tags such as `<sprite>`, `<material>`, `<font>`, etc. for text?
