### ISSUE TITLE
No Soft Mask settings available in Unity 2022.3.19f1

### ISSUE THREAD

**Issue by hexenwerkgames** [mob-sakai/SoftMaskForUGUI#181]
**Description**
When I replace a standard Mask with a Soft Mask, it looks already better with the default settings. But I cannot change those settings.

In the screenshots shown on the github project page, there are some settings/sliders shown for this component: 
- downsampling
- softness range slider

 I only have the following settings:
- Source (Graphic or something else)
- Seperate Mask
- a Raycast Threshhold Slider
- Invert Mask
- Invert Outlines
- Mask Channel
This way, I cannot change the smoothness of the mask.

**To Reproduce**
1. Create a Scene
2. Create a Canvas
3. Create a UI Image
4. Select some Sprite as mask for this image
5. Create another UI Image as child of the masking image
6. Add the Soft Mask Script to the masking image

**Expected behavior**
The Soft Mask script component shows the same settings I can see in the Soft Mask project description on github.
 

**Environment (please complete the following information):**
 - Version 1.7.0
 - Platform: Windows/Mac
 - Unity version: 2022.3.19f1
 
**Additional context**
I also downloaded the sample scenes. There I cannot see the settings either. So it doesn't look to me like I forgot to add another needed component or something. I haven't touched the soft maskable shader feature yet.

But: The "soft mask" component I can add to the game objects isn't marked as "(script)" like the other soft mask scripts. This seems kinda weird to me, since in the screenshot it says (script) as well. 

So I cannot be completely sure that this is a bug and not me doing something wrong here. But maybe this is a problem with more recent Unity versions?

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
Version 1.7.0 does not exist in my package.
Also, I don't recognize those options.
Is there another "SoftMask" installed in your project?
Please attach a screenshot of the inspector.

**Comment by hexenwerkgames** [comment]
Uh, this is a bit embarassing. Indeed I had accidentally installed another Soft Mask Package instead of yours and didn't notice.

So this issue can be closed.
