### ISSUE TITLE
sprite broken the scroll view area

### ISSUE THREAD

**Issue by chiangandy** [mob-sakai/SoftMaskForUGUI#183]
Sorry to post again.
    After I solve my previous issue and run app on mobile device, it can display but when I move content in scroll view and let content to overt the viewport area it will appear the mask image over the view area. Has any idea about this?
   But when I run this in Unity mobile simulator, it has no this issue.

my environment.
mobile device - Android on Hauwei p20 pro.
Unity 2021.3.30f
Dev in APPLE silicon

![Screenshot_20240813_095425_com womo womoar](https://github.com/user-attachments/assets/d0ddabe7-b795-4aeb-abbd-bbe271b26c3b)
![Screenshot_20240813_095113_com womo womoar](https://github.com/user-attachments/assets/8e15c1ed-f58c-487d-a954-ee59b5117fce)

**Comment by chiangandy** [comment]
append more information...
mask image object setup
<img width="502" alt="截圖 2024-08-13 上午10 08 38" src="https://github.com/user-attachments/assets/991ba797-24f9-4cd4-bd3d-d033c04d67f9">
image under mask setup
<img width="501" alt="截圖 2024-08-13 上午10 08 50" src="https://github.com/user-attachments/assets/ee1e87cc-c01c-4ee0-923c-cbde0d255440">

**Comment by Mythique** [comment]
I also have issues with scroll rect since the update, and recorded a video of these issues.

@mob-sakai Let me know if you're interested in the video to help resolve the issue. I tried to send it to you privately, but I couldn't find your email address and your Twitter DM are disabled.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
I would like to know more about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
@Mythique 
sakai861104@gmail.com

**Comment by mob-sakai** [comment]
Let's try how to avoid it.

- Set ShowMaskGraghic to false.
- Insert a background image under SoftMask.

—

I think there seems to be no problem using AntiAliasing or Normal instead of MaskingMode=SoftMasking.

Please display the red circular frame in front of the icon.
It will cover the jaggies.

**Comment by chiangandy** [comment]
Yes, After I change the mask setting, issue is solved. So happy! 
Thanks for your help. Thanks a lot.

**Comment by mob-sakai** [comment]
@chiangandy 
That's great to hear.
To further investigate the issue, could you submit a minimal reproducible project?

> Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by chiangandy** [comment]
basically, I just do following thing.

Set ShowMaskGraghic to false.
Insert a background image under SoftMask.

and rebuild app than issue is solved. :)

<img width="149" alt="截圖 2024-08-16 下午2 41 58" src="https://github.com/user-attachments/assets/d49c6eff-8858-4d89-83cd-9b44dac25796">

**Comment by mob-sakai** [comment]
@chiangandy 
Apologies for any confusion.
What I'm looking for is a "minimal reproducible project" where the issue can be consistently observed.

![Screenshot_20240813_095113_com womo womoar](https://github.com/user-attachments/assets/8e15c1ed-f58c-487d-a954-ee59b5117fce)

**Comment by chiangandy** [comment]
"minimal reproducible project" means to provide the project content? Since it is a company's project which contains confidential data inside, it is difficult to provide partical code without sensitive data. If time is allow, I will create a new project to make issue to show, but it need time....

**Comment by mob-sakai** [comment]
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

**Comment by chiangandy** [comment]
I make other simple project include soft mask which can produce white the
issue for circle mask image over the rect scroll view. Please take a
reference. I hope it is useful for you. :)

REGARDS

Andy Chiang
江謝迪

[image: image.png]

mob-sakai ***@***.***> 於 2024年8月17日 週六 下午5:46寫道：

**Comment by mob-sakai** [comment]
The issue is not reproduced on my environment...
If the same issue arises, please re-open this issue.

**Comment by Mythique** [comment]
![image](https://github.com/user-attachments/assets/38e4bedd-5c5e-481f-85ec-8ba13247f163)

This issue is still happening for me too. Everything is fine in the editor, but it doesn't work on Android. The scroll view has a Mask, inside there is a container with a vertical layout group. The SoftMask game object has a child with an image loaded at runtime. These images are inside a Sprite Atlas.

![image](https://github.com/user-attachments/assets/e0297949-1f88-4e43-aa1e-c117eed91af8)

**Comment by mob-sakai** [comment]
@Mythique 
I would like to know more informations about this issue.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
@Mythique 
Temporary solution: https://github.com/mob-sakai/SoftMaskForUGUI/issues/183#issuecomment-2289998665

**Comment by Mythique** [comment]
I invited you to a private repository on GitHub, with a "minimal" reproduction. I confirm that I can see the bug when building for Windows or Android.

The scene to launch is called "Map" and can be found under "Assets/Project Assets/Scenes".

Thank you for taking the time to look into this.

**Comment by mob-sakai** [comment]
Thank you 👍

**Comment by mob-sakai** [comment]
OK, I found a way to reproduce it in the editor.
<img width="507" alt="image" src="https://github.com/user-attachments/assets/b8c4ecf1-4b2a-4814-8e4a-e560b4fc3a3c">

**Comment by mob-sakai** [comment]
This occurs when there is a SoftMask under Mask.
