### ISSUE TITLE
Soft masked image flickers or disappears when resizing canvas in editor

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/SoftMaskForUGUI#184]
> Does it occur only in the editor?

Yes and regardless of if playmode is enabled. 

> Can I attach videos or gifs?

https://github.com/user-attachments/assets/3f733bc2-a361-45b2-a737-8adeb9a0eeb5

Thank you for your quick support!

_Originally posted by @mushakushi in https://github.com/mob-sakai/SoftMaskForUGUI/issues/117#issuecomment-2290531029_

**Comment by mob-sakai** [comment]
The issue is reproduced on my environment.
This issue occurred when the Game view was in "Free Aspect" mode and the Game view was resized.

**Comment by cdanek** [comment]
Upgrading to 2.3.4 leads to the softmask'ed items to not show up at all, unfortunately. I think it's related to this issue.

![image](https://github.com/user-attachments/assets/39d0462c-f21b-44a7-a504-793c107ea762)

Disabling and re-enabling a gameobject that contains the softmask components resolves it in an older release (2.1.x), but I'm not sure of the conditions that cause the images to be disabled. 

![image](https://github.com/user-attachments/assets/69bdcddf-183b-4683-98ea-b7f153805852)

Is there anything I'd need to do when migrating to 2.3.4 from 2.1.x? 

Let me know what information I can provide to help debug.

**Comment by cdanek** [comment]
Additional info: Changing the MaskingMode from "Soft Masking" to "AntiAliasing" works.

**Comment by mob-sakai** [comment]
@cdanek 
Thank you for your reporting!
Let's discuss in another issue: #196
