### ISSUE TITLE
Can softmask work with UIEffect?

### ISSUE THREAD

**Issue by TheFBplus** [mob-sakai/SoftMaskForUGUI#186]
I tried to modify the UIEffect shader as the documentation says:
![image](https://github.com/user-attachments/assets/0327f852-a828-48dc-8786-d78156a2eb5f)
but then I got this error
![image](https://github.com/user-attachments/assets/fecdd136-2e31-489c-bc9b-23c7dccf4cad)
Is there any additional setup to work with UIEffect plugin?
plugin version:
UIEffect: 4.0.0-preview.10
SoftMaskForUGUI: 2.2.1

**Comment by mob-sakai** [comment]
Ah, well, UIEffect hasn't been updated in a while, so it doesn't currently support soft masking. I see the demand for this feature and it will probably be supported in the future.
