### ISSUE TITLE
SoftMask darkens TextMeshPro Texts Colored Outlines

### ISSUE THREAD

**Issue by eroanasu** [mob-sakai/SoftMaskForUGUI#187]
Would like to use a SoftMask on a Container which could have text (TMP) with an colored outline.
However, it seems to make that outline color darker when on a SoftMask.
Is this a bug?
The color values on the Material itself is exactly the same, only the visible output changes.

Softmask disabled:
![image](https://github.com/user-attachments/assets/ffc23a30-a1a7-4012-b3f1-4e40beecd54b)

Softmask enabled:
![image](https://github.com/user-attachments/assets/b9b95388-53ce-452e-a61d-48a3f951aa7e)

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Tell me about your develop/build environment.
 - version [e.g. 2.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2022.2.0f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP/HDRP]

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
README: https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#usage-with-textmeshpro

**Comment by eroanasu** [comment]
SoftMask Version 2.2.2
Platform: Windows, but will also build for iOS and Android
Unity version: 2022.3.20f1
Build options: URP

I've also tested on older version (2021.3.37f1) of Unity and SoftMask version 1.0.2 and had the same results.
TMP Essentials and TMP Support for ugui 2.0 also included.
[TextOutlineSample.zip](https://github.com/user-attachments/files/16690461/TextOutlineSample.zip)

**Comment by mob-sakai** [comment]
Thank you.
The issue is reproduced on my environment.

**Comment by mob-sakai** [comment]
@eroanasu 
Please re-import the shader following the [guide](https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#usage-with-textmeshpro).

**NOTE:** In your environment (Unity 2022.3.20f1), please select `TextMeshPro Support` instead of `TextMeshPro Support (ugui 2.0)`.
![](https://github.com/user-attachments/assets/6182396f-65db-489e-a5ea-e5e2d5b693a9)
