### ISSUE TITLE
I just Disable/Enable the MaskShape's Parent and the MaskShape not work.

### ISSUE THREAD

**Issue by gabrielchen0314** [mob-sakai/SoftMaskForUGUI#189]
I just Disable/Enable the object and the MaskShape not work.
![image](https://github.com/user-attachments/assets/14f66d74-500e-4604-b0ad-947598e06148)
Close Object
![image](https://github.com/user-attachments/assets/dc03fa3e-ca8e-41a8-bb80-b93b20feaf30)
Show Object
![image](https://github.com/user-attachments/assets/4e1ee138-3cc6-4198-a14d-f7861391c9c3)
And MaskShape not work

**Comment by gabrielchen0314** [comment]
Image_SoftMask
![image](https://github.com/user-attachments/assets/4288a774-4b13-4ea9-9f1d-4f437f7ca637)

Image_Masking Shape
![image](https://github.com/user-attachments/assets/3efaef10-e263-47f2-813e-3559d14e76eb)

**Comment by gabrielchen0314** [comment]
if you just Disable/Enable Image_Masking Shape, Masking Shape can Work.
but if you Disable/Enable Image_Masking Shape's Parent, Masking Shape not work.

**Comment by bodardr** [comment]
Hey so I have the same issue it seems that the parent's maskDepth is stuck at -1. I couldn't find a way to force it to 0.
Somehow changing the mask parent's image alpha makes the mask work but I can't do it via scripting. I've resorted to another solution that doesn't use soft masks but oh well. 

If a fix is found I'll try it.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by gabrielchen0314** [comment]
Here
[MaskShape not work.zip](https://github.com/user-attachments/files/16791542/MaskShape.not.work.zip)

**Comment by mob-sakai** [comment]
Thank you 👍
