### ISSUE TITLE
Doesn't work with 2018.3 Text Mesh Pro Package

### ISSUE THREAD

**Issue by strich** [mob-sakai/SoftMaskForUGUI#19]
Just tried pulling the latest and various shaders try to include Text Mesh Pro cginc files that don't exist as they are managed by Package Manager in /Packages/*

Repro: Try to add your project to a new 2018.3 project with Text Mesh Pro installed via the package manager.

**Comment by mob-sakai** [comment]
Hi @strich 
Thank you for reporting!

**Comment by mob-sakai** [comment]
Text Mesh Pro requires "TMP Essential Resources".
"TMP Essential Resources" contains shaders, fonts, materials, SpriteAsset, etc. for Text Mesh Pro.
If "TMP Essential Resources" is not in the project, Text Mesh Pro will not work.

Click 'Window> TextMeshPro> Import TMP Essential Resources` from menu.
![](https://user-images.githubusercontent.com/12690315/50266746-28417880-0468-11e9-9672-36eb9563c87c.png)

**Comment by strich** [comment]
Cheers!
