### ISSUE TITLE
Shader Graph Support

### ISSUE THREAD

**Issue by GID0317** [mob-sakai/SoftMaskForUGUI#190]
**Describe what help do you need**
While creating a UI shader with Shader Graph using the sprite unlit option, if you attempt to apply a mask, the Shader Graph disappears. Is there a method to integrate the mask into the Shader Graph? Thank you.

**Comment by mob-sakai** [comment]
For now, **NO**.
Honestly, I'm not technically familiar with Shader Graph...
But I do think supporting custom nodes would be a good idea. 👍

**Comment by mob-sakai** [comment]
I have done some research on ShaderGraph.
I have created a generic SoftMask subgraph that will be released soon.
![](https://github.com/user-attachments/assets/979f1b81-26d5-44af-9275-24dd2db1c62e)

**Comment by GID0317** [comment]
That was incredible! This is going to be a game-changer!

**Comment by mob-sakai** [comment]
Thanks. 👍 
If you are interested you can try the pre-release version.

```
"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src#develop",
```

**Comment by mob-sakai** [comment]
See https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#usage-with-shadergraph

**Comment by GID0317** [comment]
Hi, after testing the latest pre-release version of SoftMaskForUGUI (develop branch https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src#develop), it appears that the Shader Graph support is listed as 0kb (And now the main release too). do you know how to fix this?

![image](https://github.com/user-attachments/assets/0a2d85cb-d84f-4ce2-a2cc-77fbaf7db30c)

[Package Manager Window] Cannot import sample ShaderGraph Support: The path d:/unityproject/Project/Library/PackageCache/com.coffee.softmask-for-ugui/Samples~/ShaderGraph Support does not exist.

**Comment by mob-sakai** [comment]
Sorry, I'll fix it asap.

**Comment by mob-sakai** [comment]
Please try version 2.3.1

**Comment by GID0317** [comment]
Thank you! Now it has been fixed in the version 2.3.1
![image](https://github.com/user-attachments/assets/2a7a087b-f9fa-4039-989c-f39f3aa7cb3b)

**Comment by GID0317** [comment]
It seems I've encountered a bug after testing. it appears that the bug only occurs when using the Soft Masking mode, which sometimes causes an unknown square to mask some sides of the image that we want to mask.
Masking mode: Soft Masking
UIDefault (SoftMaskable):
<img src="https://github.com/user-attachments/assets/3cf2d28c-f650-4979-931d-3f125cf1f56e" width="300" />
Custom ShaderGraph shader:
<img src="https://github.com/user-attachments/assets/8fb6b81b-6362-4e64-8fed-5d2a3a1d4a18" width="300" />

The other mode appears to be normal.
Masking mode: Anti Aliasing
<img src="https://github.com/user-attachments/assets/0e593bd3-c888-4316-abb7-58e0d75f7ae3" width="300" />
Masking mode: Normal
<img src="https://github.com/user-attachments/assets/fbdea78f-a558-4326-bea6-5bb74d107290" width="300" />

I have already tried testing it on the new scene, and the bug appears there as well, but it's not as noticeable as in the current scene I'm using.

**Comment by mob-sakai** [comment]
Thank you.
Let's discuss in another issue. #191
