### ISSUE TITLE
ShaderGraph is not working correctly

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/SoftMaskForUGUI#191]
It seems I've encountered a bug after testing. it appears that the bug only occurs when using the Soft Masking mode, which sometimes causes an unknown square to mask some sides of the image that we want to mask.
Masking mode: Soft Masking
UIDefault (SoftMaskable):
<img src="https://github.com/user-attachments/assets/3cf2d28c-f650-4979-931d-3f125cf1f56e" width="300" />
Custom ShaderGraph shader:
<img src="https://github.com/user-attachments/assets/8fb6b81b-6362-4e64-8fed-5d2a3a1d4a18" width="300" />

The other mode appears to be normal.
Masking mode: Anti Aliasing
<img src="https://github.com/user-attachments/assets/0e593bd3-c888-4316-abb7-58e0d75f7ae3" width="300" />
Masking mode: Normal
<img src="https://github.com/user-attachments/assets/fbdea78f-a558-4326-bea6-5bb74d107290" width="300" />

I have already tried testing it on the new scene, and the bug appears there as well, but it's not as noticeable as in the current scene I'm using.

_Originally posted by @GID0317 in https://github.com/mob-sakai/SoftMaskForUGUI/issues/190#issuecomment-2330952720_

**Comment by GID0317** [comment]
Alright, I'll send over the project files later after finishing moving the files to minimal project

**Comment by GID0317** [comment]
develop/build environment:
- version: 2.3.1
- Platform: Editor(Windows 11 23H2), Android
- Unity version: 6000.0.17f1 (Unity 6 Preview)
- Build options: IL2CPP, .Net Framework, URP 17.0.3

And here the minimal project files.
[ShaderGraphBugReport.zip](https://github.com/user-attachments/files/16887749/ShaderGraphBugReport.zip)

**Comment by mob-sakai** [comment]
Thank you!

**Comment by mob-sakai** [comment]
Condition:
- URP
- `Canvas.renderMode = ScreenSpaceCamera`

**Comment by mob-sakai** [comment]
Sorry.
Part of my report was a misunderstanding.

**Comment by GID0317** [comment]
Thank you for the update. It seems that using Shader Graph with soft mask support along with Canvas.renderMode set to ScreenSpaceCamera can lead to this bug occurring. Are there any workarounds for this issue?

**Comment by mob-sakai** [comment]
> Are there any workarounds for this issue?

**Not at the moment.**

Additionally, with `Vulkan API`, it may be not rendered correctly when the screen rotates.
We might need to use UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION.
https://github.com/mob-sakai/SoftMaskForUGUI/blob/2.3.3/Shaders/SoftMask.cginc#L50-L61

**Comment by mob-sakai** [comment]
Maybe we should implement a `RendererFeature` to fix this.
I don`t know much about RP, but this is a good opportunity to learn.

**Comment by GID0317** [comment]
Sounds like a good plan! I’m not too familiar with RP RendererFeature either, but it’s indeed a great chance to learn. But I think there’s no need to rush since it only affects Canvas.renderMode set to ScreenSpaceCamera with the soft mask mode. We can use another two-mode left that works for now!

**Comment by mob-sakai** [comment]
WIP: With a custom RendererFeature, soft masking works correctly in the GameView, and the stencil is enabled in the SceneView.  
Umm, it is not perfect... but it provides a slightly improved editor experience.

![](https://github.com/user-attachments/assets/49457de3-4fc7-40fe-9143-d85574b3fdb6)

**Comment by mob-sakai** [comment]
If you are interested you can try the RC version.

```
"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src#develop",
```

For details, see https://github.com/mob-sakai/SoftMaskForUGUI/tree/develop/Packages/src#usage-with-shadergraph

**Comment by GID0317** [comment]
Sure, I'll give it a try later

**Comment by GID0317** [comment]
Great! It seems the issue has been resolved after trying out the latest RC version
![image](https://github.com/user-attachments/assets/31d8ceb5-f84c-46a8-bc21-fc2482eed17e)
