### ISSUE TITLE
SetDirtyAndNotify causes null exceptions on GameObject delete

### ISSUE THREAD

**Issue by PixelSolve** [mob-sakai/SoftMaskForUGUI#192]
**Describe the bug**
Sometimes when I delete on Initialization some GameObjects containing the SoftMask.cs component, I am getting null exceptions. Those are being casued by the call to MaskUtilities because those are not checking if the object still exists:

`
private void SetDirtyAndNotify()
        {
            SetSoftMaskDirty();
            MaskUtilities.NotifyStencilStateChanged(this);
        }
`

I solved it by just adding `if (isDirty || !this || !isActiveAndEnabled) return;` before the MaskUtilities call, but there is probably some better way to solve it.

Thank you for developing this asset by the way, it's super helpful, it's honestly crazy that Unity doesnt support this by default.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
