### ISSUE TITLE
Word canvas does not work correctly in build

### ISSUE THREAD

**Issue by oktayturkdagli** [mob-sakai/SoftMaskForUGUI#194]
**Describe the bug**
There is no problem in Editor mode and Runtime, but in the android(API 33)(IL2CPP or Mono doesn't matter) build the mask is not displayed correctly in the world canvas.

**To Reproduce**
I have no idea how to reproduce this bug.

**Environment:**
 - Version: 2.3.3
 - Platform: Mac
 - Unity version: Unity 2022.3.45
 - Build options: [ IL2CPP, .Net 4.x, URP, Android(API 33)]

**Comment by oktayturkdagli** [comment]
Unfortunately I cannot provide additional information as the project is too big :/

**Comment by oktayturkdagli** [comment]
This is a project with project settings by the company, in the build the mask and the masked image are not visible at all, if I check the box show mask image then only the mask is visible but not the masked image. In a smaller project that I'm just trying out, everything works great. Which settings should I pay attention to.

**Comment by mob-sakai** [comment]
If you need a quick fix, please try using `AntiAliasing` instead of `MaskingMode=SoftMasking`.
![](https://github.com/user-attachments/assets/6edfb187-60c5-49ec-ae51-9b82fff472f5)

**Comment by mob-sakai** [comment]
I would like to know more about this issue.

- Does this issue also occur in `Screen Space - Overlay` or `Screen Space - Camera` modes?
- Are you using URP (Universal Render Pipeline)?
- Are you using ShaderGraph?
- Are you using the `RGB ETC1 (+ Split alpha channel)` texture format?
  - That format is not supported. 
  - For details, see https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#warning-limitations

**Comment by oktayturkdagli** [comment]
- Does this issue also occur in Screen Space - Overlay or Screen Space - Camera modes?
 + No, the mask works correctly in these modes
- Are you using URP (Universal Render Pipeline)?
 + Yes
 - Are you using ShaderGraph?
+ I don't know, I'll look into it.
Are you using the RGB ETC1 (+ Split alpha channel) texture format?
- I've tried all ETC2 formats, including ETC2 8Bit. The result is the same.

**Comment by mob-sakai** [comment]
Thank you. Continue to ask questions:

- Do you use materials other than `UI/Default` for masked Graphics?
- See `Project Settings > UI > Soft Mask > Included Shaders`. Are the shaders set correctly?
- If possible, please attach a screenshot (replace the texture if necessary) or the inspector.

**Comment by oktayturkdagli** [comment]
Do you use materials other than UI/Default for masked Graphics?
**No, I didn't, I even used simpler primitive images to try it out, but the result was the same.**
See Project Settings > UI > Soft Mask > Included Shaders. Do you know if the shaders set correctly?
**Yes, the shaders seem to be correct (4 by default)**
If possible, please attach a screenshot (replace the texture if necessary) or the inspector.
**I can't take screenshots because I don't have access to the project right now. But what I'm doing is simply a mask photo (it's definitely a 9slice photo), plus the photo to be masked as the child of this mask. Then add softmask to the mask and get build.I also copied and pasted the whole projectsettings folder from another project where the soft mask was already working and the result is the same. I deleted and reinstalled the libraries and the same. I deleted the softmask, closed the project, reopened it, reinstalled the softmask and the result is the same.**

**Comment by mob-sakai** [comment]
Thank you for your response. 👍 

> Also, I usually do my experiments on the sample project and when I check the world canvas, the soft mask is broken. So you can try it on the sample project.

Umm... that is **not** reproduced on my environment...
- Version: 2.3.3
- Platform: Mac
- Unity version: Unity 2022.3.45
- Graphic API: Vulkan/OpenGLES3
- Texture format: ETC2
- Sprite mode: Sprite Atlas V2

1. I'd like you to try something. Please test the following versions:
   - 2.3.4 (latest version)
   - 2.2.4 (previous minor version)

2. Could you attach the `ProjectSettings` directory and the URP assets from your project?
Alternatively, does the issue still occur in a new project using those settings?
If the problem lies in any of the `ProjectSettings` or URP assets, it should reproduce as well.

3. The demo scene includes a sample that displays the softmask buffer.
How does it appear on your Android device?  
This will help identify which part of the process (softmask buffer generation, shaders, etc.) is causing the issue.

**Comment by oktayturkdagli** [comment]
Your First Answer:
Thank you for your reporting!
If you need a quick fix, please try using AntiAliasing instead of MaskingMode=SoftMasking.

> Yes, this works as a temporary solution.

1. I'd like you to try something. Please test the following versions.

>  I tried with both versions and the result is the same (also 2.3.5). By the way, after update 2.3.5 the masks now appear pink, when I switch to anti alising mode they appear correctly.

<img width="780" alt="Ekran Resmi 2024-09-16 09 33 40" src="https://github.com/user-attachments/assets/5dd8ce3d-e1c2-4dc7-b94d-4b8cdd577a9d">

<img width="780" alt="Ekran Resmi 2024-09-16 09 33 56" src="https://github.com/user-attachments/assets/32c6595b-11e5-49af-97b0-ff231ef3c37c">

2. Could you attach the ProjectSettings directory and the URP assets from your project?

>  I haven't tried this, I'll try it right away and write.
[ProjectSettings.zip](https://github.com/user-attachments/files/17009258/ProjectSettings.zip)

3. The demo scene includes a sample that displays the softmask buffer.

> I'll try this right away and write.

**Comment by mob-sakai** [comment]
> By the way, after update 2.3.5 the masks now appear pink, when I switch to anti alising mode they appear correctly.

Wow, what a big mistake.
I'll fix it right away.

**Comment by mob-sakai** [comment]
please try version 2.3.6.

**Comment by oktayturkdagli** [comment]
That's fast, you're great, and I'm going to try some of the experiments you suggested.

**Comment by oktayturkdagli** [comment]
By the way, there was a shader graph in the project. it was made with amplify.

**Comment by oktayturkdagli** [comment]
Oh great I was able to reproduce the problem. I'm sending it now.

**Comment by mob-sakai** [comment]
Great!
Thank you so much for your amazing help!

**Comment by mob-sakai** [comment]
That issue was reproduced on my Android as well! 👍

**Comment by mob-sakai** [comment]
I have found the cause of the problem.
If the `Render Scale` in the `Universal Render Pipeline Asset` is not set to `1.0`, the problem occurs.
(Let's try!)

![](https://github.com/user-attachments/assets/a700bb69-114a-41bc-b6df-992fe142a198)

**Comment by oktayturkdagli** [comment]
You're the best.

**Comment by mob-sakai** [comment]
Similarly, the same issue occurred when using [Dynamic Resolution](https://docs.unity3d.com/Manual/DynamicResolution.html).
I will add a new option "Use Dynamic Resolution (default: false)" to the ProjectSettings to support both `Dynamic Resolution` and `Render Scale`.

**Comment by oktayturkdagli** [comment]
That's great! I can't wait to try it. 👏👏👏

**Comment by oktayturkdagli** [comment]
Any news?

**Comment by mob-sakai** [comment]
Hi.
Sorry for the late reply.
I was struggling with an edge case regarding **dynamic resolution.**
I finally decided to omit it.

The RC version only supports `UniversalRenderPipelineAsset.renderScale`.
This is not an option, it is automatically enabled.
Please try it.

```
"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src#develop",
```

**Comment by oktayturkdagli** [comment]
Hi, I haven't had a chance to try it because there has been a big rush in recent days. 
I plan to try it tomorrow.

**Comment by oktayturkdagli** [comment]
Unfortunately, I couldn't try today and tomorrow is the weekend here. I hope a stable solution will be found by Monday, but if not I will try this RC and report back.

**Comment by mob-sakai** [comment]
@oktayturkdagli 
Oh, sorry, I forgot to push.
The RC version is now available in the `develop` branch.

**Comment by oktayturkdagli** [comment]
I confirm that the world canvas and Camera canvas problems are solved, but **this version breaks the overlay** canvas. This also breaks many other features such as alpha hit test, nested soft masking, transform sensitivity.

![softmask](https://github.com/user-attachments/assets/df190ce5-d50d-42dd-ab07-071c651fd2d4)

**Comment by mob-sakai** [comment]
@oktayturkdagli 
Thank you for your feedback!

**Comment by mob-sakai** [comment]
@oktayturkdagli 
I’ve updated the `develop` branch. Please give it a try! 👍
