### ISSUE TITLE
MaskingShapeContainer NullReferenceException

### ISSUE THREAD

**Issue by oktayturkdagli** [mob-sakai/SoftMaskForUGUI#195]
**Describe the bug**
When I download and open the sample project, I get the following error

**Error**
NullReferenceException: Object reference not set to an instance of an object
ComponentExtensions.GetOrAddComponent[T] (UnityEngine.Component component) (at <734ecb08eb9a4402b863c255b1bbf838>:0)
Coffee.UISoftMask.MaskingShape.UpdateContainer () (at ./Library/PackageCache/com.coffee.softmask-for-ugui@64f0421d11/Runtime/MaskingShape/MaskingShape.cs:374)
Coffee.UISoftMask.MaskingShape.OnDisable () (at ./Library/PackageCache/com.coffee.softmask-for-ugui@64f0421d11/Runtime/MaskingShape/MaskingShape.cs:186)

**Screenshots**
<img width="1161" alt="Ekran Resmi 2024-09-13 21 05 46" src="https://github.com/user-attachments/assets/76ce4088-9798-47dc-a3b4-c37b61c1182e">

**Environment:**
 - Version [2.3.3]
 - Platform: [Editor(Windows/Mac)]
 - Unity version: [2022.3.45f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP]

**Comment by mob-sakai** [comment]
Thank you for your reporting!
