### ISSUE TITLE
Alias name conflict

### ISSUE THREAD

**Issue by Serogriff** [mob-sakai/SoftMaskForUGUI#198]
**Describe the bug**
After upgrading to version 2.3.6, compilation fails if a project has the same type name.
`Library\PackageCache\com.coffee.softmask-for-ugui\Runtime\Utilities\SoftMaskUtils.cs(23,32): error CS0576: Namespace '<global namespace>' contains a definition conflicting with alias 'Internal'`

**Environment (please complete the following information):**
 - Version [e.g. 2.3.6]
 - Platform: Editor(Windows)
 - Unity version: [e.g. 6000.0.19f1]

**Comment by mob-sakai** [comment]
Thank you for your reporting!
