### ISSUE TITLE
The ability to disable the auto-adding of the "SoftMaskable" component on certain game objects.

### ISSUE THREAD

**Issue by DA-Assets** [mob-sakai/SoftMaskForUGUI#202]
Starting from version 2.0, SoftMaskable has been automatically added to all child components, which is very convenient. However, if among the child components there are components using custom shaders (for example, the shader from the Procedural Image asset), this shader gets replaced by the SoftMaskable shader, causing the procedural image to break.

I suggest creating a script like `IgnoreSoftMask.cs` or something, so that if this script is present on a specific game object, the SoftMaskable script won't be added to it.

Thank you!

**Comment by mob-sakai** [comment]
Thank you for your reporting!
That sounds convenient!

**Comment by mob-sakai** [comment]
**Quick workaround:**

Normally, if the SoftMaskable shader is not found, it will fall back to `Hidden/UI/Default (SoftMaskable)`.  
By setting `ProjectSettings > UI > SoftMaskable > Fallback Behaviour` to `None`, it will not fall back.

![](https://github.com/user-attachments/assets/96dda4b5-642c-4074-859f-b5a3cd9f6326)

**Comment by DA-Assets** [comment]
Thank you, it worked!
