### ISSUE TITLE
Subtract method does not look smooth

### ISSUE THREAD

**Issue by oktayturkdagli** [mob-sakai/SoftMaskForUGUI#203]
**Describe the bug**
Subtract method does not look smooth. Also the inside image is not visible in subtracted image (just solving with adding additive softmask shape component in inside image).  Also, the opacity and color settings of the inner image are distorted and do not reflect the true values.

**Screenshots**
<img width="1756" alt="Subtract Bug" src="https://github.com/user-attachments/assets/f6b953fc-dd4d-4860-a2b0-aca25e4cfb78">
<img width="1878" alt="Subtract Inner Bug" src="https://github.com/user-attachments/assets/4d06ea0f-9888-431f-9b8a-729fc76838e1">
<img width="1098" alt="Canvas" src="https://github.com/user-attachments/assets/7c396192-39c2-4b24-82df-2639e3ad6bd7">

**Environment (please complete the following information):**
 - Version [2.4.0]
 - Platform: [Editor(Windows/Mac)]
 - Unity version: [2022.3.52f1]
 - Build options: [IL2CPP, .Net 4.x, URP, HDRP]

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

**Comment by oktayturkdagli** [comment]
Thanks for the response, I avoided it because it would take time to create a new project and reproduce it, but I figured you would want it 😅. I will create a test project as soon as I can.

**Comment by oktayturkdagli** [comment]
Firstly, I apologise for the late reply, I have been going through a really busy period.
I don't know how it happened, but the problem with jagged visualisation seems to have been solved.
I took the final version of the package and I'm using it.

But I noticed some other problems:
 - Even though I set the Show Mask Graphic checkbox true in the Masking Shape components of the subtractors, it does not show the graphic. 
 - Also please play with the alpha values of the subtractors. You will see that this does not work correctly.
 
 You can find the project files and a sample video below.
 [SubtractProblem.zip](https://github.com/user-attachments/files/17657044/SubtractProblem.zip)

https://github.com/user-attachments/assets/8d3ba0e2-adde-4050-b04a-37e06546b1cd

**Comment by mob-sakai** [comment]
The stencil isn’t functioning properly.  
This will likely require a significant overhaul of the MaskingShape system... 🤔

**Comment by mob-sakai** [comment]
Is this the output you expected?
![](https://github.com/user-attachments/assets/92828205-ddaa-4523-b1b8-f85cd2b58d23)

**Comment by mob-sakai** [comment]
Please try the release candidate package. 😃

```json
"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src#develop-preview"
```

**Comment by oktayturkdagli** [comment]
I've actually shown the exact image of what I want in the example below. The circles completely cut out the masked images behind them. So that when it is made semi-opaque, the back will be seen correctly.

In this branch, the inner image is not visible. Also, when the masked image is made half opaque, the desired image is not obtained.

<img width="729" alt="Ekran Resmi 2024-11-15 09 14 24" src="https://github.com/user-attachments/assets/cdbfaf8c-bc3c-426c-a99b-d1c641b562ba">

**Comment by mob-sakai** [comment]
Ah, I understand your intention.
In other words, you want to avoid the "see-through" effect between the foreground and background when making it translucent, correct?

The simplest and fastest method is to pre-clip the texture, as you demonstrated with the "MyAim/SubtractedImage" object.
![](https://github.com/user-attachments/assets/b284be23-688c-49bb-893f-e4c9638a4faa)


The next easiest method is to emulate the "MyAim/SubtractedImage" object using a MaskingShape.
However, note that the two buttons will not be affected by the MaskingShape.


![](https://github.com/user-attachments/assets/74c7a989-bd66-42e2-bbe3-44ba941f77fa)
![](https://github.com/user-attachments/assets/73677d54-f417-4422-8412-a4a8b2683ca8)
[scene.zip](https://github.com/user-attachments/files/17774322/SubtractTestScene_fix.unity.zip)
