### ISSUE TITLE
ArgumentException: RenderTextureDesc width must be greater than zero when setting the Down Sampling Rate to X8.

### ISSUE THREAD

**Issue by goblon17** [mob-sakai/SoftMaskForUGUI#204]
**Describe the bug**
When setting Down Sampling Rate to X8 in Soft Mask component `ArgumentException: RenderTextureDesc width must be greater than zero` is thrown.

**To Reproduce**
1. Go to the demo scene.
2. Select any object with Soft Mask component.
3. Change Down Sampling Rate in Soft Mask component to X8

**Screenshots**
https://github.com/user-attachments/assets/55f9a069-1301-40ef-869c-577baa90256e

**Environment (please complete the following information):**
 - Version 2.3.8
 - Platform: Editor(Windows)
 - Unity version: 2022.3.26f1
 - Build options: Mono, URP

**Comment by mob-sakai** [comment]
Thank you for your reporting!
