### ISSUE TITLE
Smaller element masked differently from another with mask

### ISSUE THREAD

**Issue by NibbleByte** [mob-sakai/SoftMaskForUGUI#205]
**Describe the bug**
I have a ScrollRect with mask to soften the edges. Inside I have "level icons" that are circles with mask to cut out the rectangular sprite into circle. In front of each circle, there is a paper element with score. That paper element is masked (faded) differently from the circle, allowing the circle to be visible from underneath. I'm not sure if I have bad setup or this is how it is supposed to work.
![image](https://github.com/user-attachments/assets/6f456511-183e-4810-8181-34f25291511e)

Additional bug that may be related. When I increase the softness range of the scroll view mask, I get this visual artifact (clear circle inside the circle):
![image](https://github.com/user-attachments/assets/8d3ad0e8-7cbb-4fb8-a3e3-8bd39568bc6f)
This may be related to the circle foreground image:
<img src="https://github.com/user-attachments/assets/0dabac69-600a-40b5-90a7-792a777cb033" width="128">

**To Reproduce**
1. Download this sample project: https://drive.google.com/file/d/126l7p4nG6ouXf4uJh9AkrZdmUP9og8fY/view?usp=sharing
2. Run it and open the "PaperMap" scene
3. Play the scene.
4. Scroll up and down until some paper element with circle gets to the bottom edge of the scroll view.
5. Increase the "Viewport" softness range.

**Expected behavior**
* Circle and paper element should blend together - circle behind paper element should not be seen.
* No "clear circle in circle" artifact.

**Environment (please complete the following information):**
 - Version 2.3.3 (as 2.3.4 and above cause compiler error on ShaderGraph for me).
 - Platform: Editor Windows
 - Unity version: 2023.2.9f1
 - Build options: URP

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
> I'm not sure if I have bad setup or this is how it is supposed to work.

It is a specification.
However, as you mentioned, it does look unnatural.
I’ll look into ways to improve the appearance. 👍 

For example, a method to compensate for soft mask magnification:

![Oct-30-2024 10-16-00](https://github.com/user-attachments/assets/80091924-1aa6-4188-a0e5-5432b1920d9d)

![PaperMap_-_SoftMask_205_-_Windows__Mac__Linux_-_Unity_2023_2_20f1__Metal__compressed](https://github.com/user-attachments/assets/0f35759b-650c-45ca-858d-7e873c59ccc6)

> When I increase the softness range of the scroll view mask, I get this visual artifact (clear circle inside the circle):

In the latest version it has been fixed.

> as 2.3.4 and above cause compiler error on ShaderGraph for me

Oops, it's my mistake.
I'll create a new issue later.

**Comment by NibbleByte** [comment]
Yes, this looks better, it will be nice to have, although my design has changed and I no longer have this paper element in front. :D

I haven't created ticket for the compiler errors, because I'm not using LTS version, so I don't expect everything to work great. I'll soon upgrade to Unity 6 and get the latest version of the plugin.

**Comment by mob-sakai** [comment]
> as 2.3.4 and above cause compiler error on ShaderGraph for me

This issue was fixed in version 2.3.9. 👍

**Comment by mob-sakai** [comment]
> Yes, this looks better, it will be nice to have, although my design has changed and I no longer have this paper element in front. :D

This enhancement has been released in version 2.4.0. 👍

**Comment by NibbleByte** [comment]
I downloaded that version in the sample project and it seems increasing the power just makes it worse. I wish to go below 1? Or am I using it wrong?
![SoftMaskPowerUsageIssue](https://github.com/user-attachments/assets/ed3cfa48-e0db-45af-8f97-dda34a655feb)

**Comment by mob-sakai** [comment]
Adjust the Foreground_Frame’s power.

**Comment by NibbleByte** [comment]
Ah yes, silly me. That works, thank you.

I have another small editor issue. Sometimes (for example when I just started the sample project), when tweaking the Power value while the game is running, everything in the soft mask stops drawing. Maximizing the game view (i.e. changing the resolution?) fixes it.
![SoftMaskNotDrawing](https://github.com/user-attachments/assets/d7e39577-89df-41a4-9714-59a147a4e3f8)

Similar thing happens on my original project, often when switching between fullscreen and window and clicking/drag the scrollview? - softmask stops drawing. To go fullscreen I use the [Fullscreen Editor](https://assetstore.unity.com/packages/tools/utilities/fullscreen-editor-69534) plugin, but I don't think it's related. (in the gif, I switch to fullscreen via hotkey, so the whole image changes suddenly multiple time).

![SoftMaskNotDrawing2](https://github.com/user-attachments/assets/080c18e5-fde2-482e-8e12-98ad2fad10ae)

_(sorry for hijacking the issue, maybe create another issue? 😄 )_

**Comment by mob-sakai** [comment]
Oh...
I would like to know more about this issue.
Could you please create a new issue?
(Please attach a minimal reproducible project.)

Thank you 👍
