### ISSUE TITLE
How does the anti-aliasing version works ?

### ISSUE THREAD

**Issue by lgarczyn** [mob-sakai/SoftMaskForUGUI#207]
I've looked through the code, but I can't find anywhere how the AA version works.

It's not a render texture per the Readme, but I don't see how you can use a stencil to do this kind of effect.

**Comment by mob-sakai** [comment]
The basic principles of AA masking mode can be easily tested even without SoftMaskForUGUI.

First, here’s the default Mask.  
As you can see, the jagged edges are clearly visible.  
![](https://github.com/user-attachments/assets/b343ceac-4b37-40c9-9108-bdc1f763a188)

Next, let’s try reducing `Image.color.a`.  
Surprisingly, the jagged edges become less noticeable.  
This is because the clipping sensitivity indirectly increases.  
![](https://github.com/user-attachments/assets/a5f9cf5e-cad3-41e9-9007-70ed64cc49af)

However, as it stands, it will disappear when `CanvasGroup.alpha` is reduced, so a bit more adjustment is needed.

**Comment by lgarczyn** [comment]
I feel like I must be missing some important points, but wouldn't reducing the image.color.a just... Make the image transparent?

**Comment by mob-sakai** [comment]
The `Image.color.a` I’m referring to is the masking graphic (i.e., a graphic with a Mask component).

In the `UI/Default` shader, the stencil mask is implemented as follows:

```cginc
#ifdef UNITY_UI_ALPHACLIP
clip (color.a - 0.001);
#endif
```

In other words, pixels with an alpha value near zero are clipped.  
Looking at the alpha histogram of the masking graphic, there’s a noticeable gap at an alpha value of 0, which results in jagged edges.
![](https://github.com/user-attachments/assets/3b36b83f-c090-484b-a191-002107c26a10)

Now, let’s try multiplying the alpha by a small value.  
The gap becomes smaller than before, and the edges are now smooth, without jagged.
![](https://github.com/user-attachments/assets/b71d28a0-6534-4b39-ba88-200d285905e5)

**Comment by lgarczyn** [comment]
> The `Image.color.a` I’m referring to is the masking graphic (i.e., a graphic with a Mask component).
> 
> In the `UI/Default` shader, the stencil mask is implemented as follows:
> 
> ```cginc
> #ifdef UNITY_UI_ALPHACLIP
> clip (color.a - 0.001);
> #endif
> ```
> 
> In other words, pixels with an alpha value near zero are clipped.  
> Looking at the alpha histogram of the masking graphic, there’s a noticeable gap at an alpha value of 0, which results in jagged edges.
> ![](https://github.com/user-attachments/assets/3b36b83f-c090-484b-a191-002107c26a10)
> 
> Now, let’s try multiplying the alpha by a small value.  
> The gap becomes smaller than before, and the edges are now smooth, without jagged.
> ![](https://github.com/user-attachments/assets/b71d28a0-6534-4b39-ba88-200d285905e5)

Right, but whatever happens, the mask still only has 1 bit of depth. Offsetting the clipping value of the mask will simply appear to grow or shrink the mask by one pixel, but shouldn't give smooth edges.

**Comment by mob-sakai** [comment]
In clipping, referencing the bilinearly interpolated pixel values for small gaps provides a stencil result with a higher resolution than the actual pixel size.

BTW, this method cannot be used with point-filtered sprites.

**Comment by lgarczyn** [comment]
> In clipping, referencing the bilinearly interpolated pixel values for small gaps provides a stencil result with a higher resolution than the actual pixel size.
> 
> BTW, this method cannot be used with point-filtered sprites.

Oh! So the clipping is still perfectly binary, but it solves the issue of a mask with too low resolution

**Comment by mob-sakai** [comment]
Exactly!
