### ISSUE TITLE
Image doesn't mask when use Unity Mask and MaskingShape

### ISSUE THREAD

**Issue by giangchau92** [mob-sakai/SoftMaskForUGUI#209]
Hi,
Thank you for creating useful tool. I got this bug when use Soft Mask
My hierarchy like that.
<img width="246" alt="image" src="https://github.com/user-attachments/assets/244d5801-e577-4754-978a-37e0beaa0ed9">

When `SoftMask-Black` inside `UnityMask-White`, everything work properly.
But when I move `SoftMask-Black` to outsize of `UnityMask-White`, red image is visible outsize of `UnityMask-White`

![image](https://github.com/user-attachments/assets/d614eebf-c806-47d5-bb5f-8d90a2e6fdf2)
[SoftMaskBug.zip](https://github.com/user-attachments/files/17610989/SoftMaskBug.zip)

**To Reproduce**
1. Open `SampleScene` scene on attachment unity project
2. Move `SoftMask-Black` around for testing
4. See error when move `SoftMask-Black` outside of `UnityMask-White`

**Environment:**
 - Version: SoftMaskForUGUI 2.4.0
 - Platform: Mac
 - Unity version: 2022.3.14f1

I believe that MaskShape stencil was not setup correctly

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
The stencil isn’t functioning properly.  
This will likely require a significant overhaul of the MaskingShape system... 🤔

**Comment by mob-sakai** [comment]
Is this the output you expected?
[](https://github.com/user-attachments/assets/89ede106-a223-44b5-acd4-c6b4b7080b86)

**Comment by gusteixeira-25** [comment]
Yes, that is exactly what I want.
I have tried to fixed this in my side. It like
<img width="792" alt="image" src="https://github.com/user-attachments/assets/b7281a30-c022-4115-9d64-9ca2d07f47fc">

<img width="886" alt="image" src="https://github.com/user-attachments/assets/9c866db3-b7ad-48cd-9a98-4071bc3763da">
But I am not sure if it would run as your designed

**Comment by mob-sakai** [comment]
Please try the release candidate package. 😃

```
"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src#develop-preview"
```

**Comment by mob-sakai** [comment]
Additionally, a few tricks were necessary to prevent soft masking from breaking.

**Comment by giangchau92** [comment]
Thank you, It works great
