### ISSUE TITLE
Raycast filtering work

### ISSUE THREAD

**Issue by LovorDev** [mob-sakai/SoftMaskForUGUI#210]
How does raycasting work? I downloaded a new version and tried the demo, but it didn't work as expected.

https://github.com/user-attachments/assets/b34691ea-04b2-4780-b9cd-3cb642b0b413

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by mob-sakai** [comment]
There was an issue with the sprite used in the demo.
Alpha hit test is not supported when the texture is in crunch format or non-readable.

I’ll add this note to the README.
