### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by PalaNolho** [mob-sakai/SoftMaskForUGUI#214]
Does this Asset work with your other asset Unmask?
My use case is to have an image filling the whole screen (in black, for example) and then have a hole in the middle that allows to see what is behind that full-screen image, and that hole has smooth/blurred edges..

![image](https://github.com/user-attachments/assets/985daf1b-b3b7-4fe3-a08d-b2d8bcf2bb41)

**Comment by mob-sakai** [comment]
It cannot work with Unmask, but it can be substituted using `MaskingShape` component (MaskingMethod=Subtract).

![Scene214_-_SoftMaskForUGUI_-_Windows__Mac__Linux_-_Unity_2021_3_30f1__Metal__compressed](https://github.com/user-attachments/assets/164c3249-44cb-44a9-97f4-e41cce732cbb)
[Scene214.unitypackage.zip](https://github.com/user-attachments/files/17958123/Scene214.unitypackage.zip)
