### ISSUE TITLE
Wrong Package Name On Releases Page UPM Install

### ISSUE THREAD

**Issue by kadaxo** [mob-sakai/SoftMaskForUGUI#215]
UPM package name is wrong on the [releases page](https://github.com/mob-sakai/SoftMaskForUGUI/releases/tag/3.0.0). This problem creates 
`An error occurred while resolving packages:
  Project has invalid dependencies:
    com.coffee.ui-effect: The requested dependency 'com.coffee.ui-effect' does not match the name 'com.coffee.softmask-for-ugui' specified in the package manifest of [com.coffee.ui-effect@https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src]` 
    this error.

"com.coffee.ui-effect": "https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src",

should be

"com.coffee.softmask-for-ugui": "https://github.com/mob-sakai/SoftMaskForUGUI.git?path=Packages/src",

**Comment by mob-sakai** [comment]
Thank you for your reporting!
