### ISSUE TITLE
Non-ASCII characters are not displayed properly with TextMeshProUGUI and SoftMask.

### ISSUE THREAD

**Issue by wiseyestudio00** [mob-sakai/SoftMaskForUGUI#216]
**To Reproduce**
1. Create a TextMeshPro FontAsset with English font, and attach non-English font to its fallback list (I am using Noto Serif)
2. Create a Canvas with RenderMode set to Camera, and attach a Camera to it.
3. Create TextMeshProUGUI component under a SoftMask parent.
4. Non-English texts are not displayed correctly (see screenshots below).

**Expected behavior**
The texts should be displayed properly.

**Screenshots**
![Screenshot_0](https://github.com/user-attachments/assets/28d4d726-23c3-4e21-8801-10d768f6f5f4)
^ English (Displaying properly)
![Screenshot_1](https://github.com/user-attachments/assets/280ef8af-d0e9-44a2-9b26-5020db82dd5e)
^ Traditional Chinese (Error)
![Screenshot_2](https://github.com/user-attachments/assets/0babb91d-c4e2-4943-a659-a19b1454edb4)
^ Japanese (Error)

![Screenshot_3](https://github.com/user-attachments/assets/64b35d9e-ae70-474e-9ed7-6618b3638ce2)
^ If I remove the SoftMask in Viewport, the error goes away.

![Screenshot_4](https://github.com/user-attachments/assets/31406e7a-6b42-42c4-baa4-68962a1a1684)
^ Setting Masking Mode to Normal works correctly, as well as Anti-Aliasing.

![圖片](https://github.com/user-attachments/assets/a70fb3c8-d46f-4f0b-9d32-143a9deb91cd)
^ How the font is set up. The font itself is a static font with ASCII characters, with 3 fallback Japanese font (first 2 static, the last is dynamic fallback).

![Screenshot_5](https://github.com/user-attachments/assets/ce0b9cfe-ba86-442e-8c8b-21a4b9a03d20)
^ Overlay causes error too; If I set the RenderCamera to overlay, the problematic texts disappear.

**Environment (please complete the following information):**
 - Version 3.0.1
 - Platform: Windows Editor
 - Unity version: 6000.0.29f1
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]
 - Unity 6 Text Mesh Pro Support is imported.

**Additional context**
I upgraded from 1.0.2, where the same error also existed.

UPDATE:
If I manually toggle on and off the "Ignore Children" option in Soft Maskable on the TextMeshProUGUI component, the texts starts rendering properly.

![圖片](https://github.com/user-attachments/assets/37c48298-5854-4892-9837-f8f26ae3d125)
^ Before toggle On
![圖片](https://github.com/user-attachments/assets/98ff8dd3-6bca-4b6b-ba93-0cd87c38bd48)
^ Toggle On
![圖片](https://github.com/user-attachments/assets/103c04ea-db2b-428c-9fec-83b3306b88ff)
^ Toggle Off (texts start displaying properly.)

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by mob-sakai** [comment]
As an alternative: Consider using RectMask2D or Anti-Aliasing mask mode.

https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#rectmask2d-vs-softmask

https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#comparison-of-masking-mode

**Comment by wiseyestudio00** [comment]
> Thank you for your reporting! Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue? Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.
> 
> ![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)


I am sorry, but this project has grown really large and it will be pretty complex & will take a long while to create a minimal project. Is it possible that I just privately share a fork of the project with you instead?

**Comment by wiseyestudio00** [comment]
> As an alternative: Consider using RectMask2D or Anti-Aliasing mask mode.
> 
> https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#rectmask2d-vs-softmask
> 
> https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#comparison-of-masking-mode

I would love to, but I also want to use the SoftMask effect, especially in other parts of the project......I am not too tight on the time constraint, so I can resolve this issue with you + I think this will really benefit SoftMask's usability with other languages! It's so close to being the perfect solution for Soft-Masking in Unity!

**Comment by mob-sakai** [comment]
> Is it possible that I just privately share a fork of the project with you instead?

Yes, that's no problem.

**Comment by wiseyestudio00** [comment]
Hi! Sorry it took a while. I just share the fork with you. To start, please start from with CompleteRestartScene, which should lead you automatically to TitleScreen, where you can access PlayerSetting Menu. Scroll to the button to change language to see the error!

**Comment by mob-sakai** [comment]
Okay, I cloned that repository. 👍

**Comment by mob-sakai** [comment]
Playing a CompleteRestartScene scene causes an error.

```
NullReferenceException: Object reference not set to an instance of an object
WiseyeStudio.Lily.Preload.PreloadMenuManager.StartAsync (System.Threading.CancellationToken cancellationToken) (at Assets/Scripts/WiseyeStudio/Lily/Preload/PreloadMenuManager.cs:57)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.Factory.cs:326)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.cs:316)
Cysharp.Threading.Tasks.UniTask+WhenAllPromise.TryInvokeContinuation (Cysharp.Threading.Tasks.UniTask+WhenAllPromise self, Cysharp.Threading.Tasks.UniTask+Awaiter& awaiter) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.WhenAll.cs:200)
--- End of stack trace from previous location where exception was thrown ---
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTaskCompletionSource.cs:244)
Cysharp.Threading.Tasks.UniTask+WhenAllPromise.GetResult (System.Int16 token) (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.WhenAll.cs:218)
Cysharp.Threading.Tasks.UniTask+Awaiter.GetResult () (at ./Library/PackageCache/com.cysharp.unitask/Runtime/UniTask.cs:316)
WiseyeStudio.Lily.Preload.PreloadSceneManager.Start () (at Assets/Scripts/WiseyeStudio/Lily/Preload/PreloadSceneManager.cs:63)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <a6d715f5ce8c4754a140b50ff638878a>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:155)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:109)
```

**Comment by mob-sakai** [comment]
The issue is reproduced on my environment.

<img width="730" alt="image" src="https://github.com/user-attachments/assets/1fa13320-917b-4a21-ba69-ac8876d5f64e" />

**Comment by mob-sakai** [comment]
This project uses a localization system.
I have modified the csv file as follows so that Japanese is displayed even when English is selected.
```csv
stage_combo_animation_title,コンボのお祝い,連擊慶祝,连击庆祝,コンボのお祝い
```
```csv
Every_X_Cobmo,{0}コンボごとに,每{0}次連擊,每{0}次连击,{0}コンボごとに
```

It appears to be displayed correctly.
![](https://github.com/user-attachments/assets/dc604e78-1be8-4594-92da-cc081669e72c)

**Comment by wiseyestudio00** [comment]
I am sorry for the error! I was trying to create a fork in a hurry, so the mistake must have slipped through. Glad to see the error being reproducible though!

**Comment by mob-sakai** [comment]
As a workaround: by deactivating the relevant objects, they were displayed correctly.

<img width="388" alt="image" src="https://github.com/user-attachments/assets/07c402cc-259a-4206-9cf9-4d14cf81ca80" />

**Comment by mob-sakai** [comment]
By adding a delay before hiding the submenu, it was displayed correctly.

```
await UniTask.Delay(500, cancellationToken: CancellationToken.None);
await HideAllSubMenuAsync(0f, CancellationToken.None);
```

Considering the previous patch (calling `gameObject.SetActive(true)` after hiding the submenu), it seems that TextMeshProUGUI is processing "something" asynchronously when activated for the first time.

**Comment by mob-sakai** [comment]
<img width="692" alt="image" src="https://github.com/user-attachments/assets/c6ed7c7c-643e-4715-8589-534faf35d4d8" />

This may be due to the SoftMaskable component being above the SubMeshUI component.

**Comment by mob-sakai** [comment]
<img width="781" alt="image" src="https://github.com/user-attachments/assets/ab038f55-6b3e-4e4f-a5c9-969702ae966b" />

PERFECT!
I will release it soon. Good night.
