### ISSUE TITLE
TextMeshPro Inverse Masking Shape (Substract) Not Working

### ISSUE THREAD

**Issue by ndumais** [mob-sakai/SoftMaskForUGUI#217]
**Describe the bug**
On version 3.0.1 (and possibly the ones prior), adding a masking shape to a GameObject with TextMeshPro (UI) component does not seem to work as expected.

I've made sure the TextMeshPro (UI) shows properly by putting it underneath in the hierarchy and removing the Masking Shape. Note that the mobile hidden soft mask shader for text mesh pro is being used and visible in the inspector (see 2nd screenshot).

**To Reproduce**
1. Import TextMeshPro support from the package manager.
2. Make a parent image with SoftMask component (and uncheck show mask graphic).
3. In childrens, add a normal text with a Masking Shape (and set to substract).
4. Still in childrens, add the image that will be masked by the text.
5. It works, the text masks the image (see 1st screenshot).
6. Add a TextMeshPro (UI) Component in the same way the Unity Text was added (you can remove disable the Unity Text).
7. Does not work.

**Screenshots**
![image](https://github.com/user-attachments/assets/960b2982-c79e-4314-a2d1-7310c0861b0c)

![image](https://github.com/user-attachments/assets/4cb8bed6-50db-4c58-a9e2-6f7b15b1bd1f)

**Expected behavior**
TextMeshPro UI with a shaping mask should behave as Unity Text if TextMeshPro support is imported.

**Environment (please complete the following information):**
 - Version 3.0.1
 - Platform: Editor (Windows)
 - Unity version: 2022.3.50f1
 - Build options: .Net 2.1

**Comment by mob-sakai** [comment]
Thank you for your reporting!
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by ndumais** [comment]
[mob-sakai-repro-0.zip](https://github.com/user-attachments/files/18142746/mob-sakai-repro-0.zip)

**Comment by mob-sakai** [comment]
Thank you!

**Comment by mob-sakai** [comment]
It will be supported in the next update. :+1:
