### ISSUE TITLE
Can I get softmask work with spine?

### ISSUE THREAD

**Issue by Schrodinger123** [mob-sakai/SoftMaskForUGUI#218]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe what help do you need**
When I put a SkeletonGraphic under SoftMask and add a Soft Maskable on it, the spine turns purple.
And if a delete material of the SkeletonGraphic, it shows. But also with some bone outline of it.

**Additional context**
<img width="660" alt="image" src="https://github.com/user-attachments/assets/5510ec38-925d-4ec6-9d76-f015727361d0" />

I don't know if there is something I missed?

**Comment by mob-sakai** [comment]
Thank you for your reporting!

Yes, currently `SkeletonGraphic` is not supported.
However, I believe it can (probably) be implemented easily. 👍

> https://github.com/mob-sakai/SoftMaskForUGUI?tab=readme-ov-file#usage-with-your-custom-shaders

**Comment by mob-sakai** [comment]
I’m planning to try it later.

**Comment by Schrodinger123** [comment]
So I updated to 3.0.1 and tried to add soft-maskable variants to Spine/SkeletonGraphic like this:
`
// This is a premultiply-alpha adaptation of the built-in Unity shader "UI/Default" in Unity 5.6.2 to allow Unity UI stencil masking.

Shader "Spine/SkeletonGraphic (SoftMaskable)"
{
	Properties
	{
		[PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
		[Toggle(_STRAIGHT_ALPHA_INPUT)] _StraightAlphaInput("Straight Alpha Texture", Int) = 0
		[Toggle(_CANVAS_GROUP_COMPATIBLE)] _CanvasGroupCompatible("CanvasGroup Compatible", Int) = 1
		_Color ("Tint", Color) = (1,1,1,1)

		[HideInInspector][Enum(UnityEngine.Rendering.CompareFunction)] _StencilComp ("Stencil Comparison", Float) = 8
		[HideInInspector] _Stencil ("Stencil ID", Float) = 0
		[HideInInspector][Enum(UnityEngine.Rendering.StencilOp)] _StencilOp ("Stencil Operation", Float) = 0
		[HideInInspector] _StencilWriteMask ("Stencil Write Mask", Float) = 255
		[HideInInspector] _StencilReadMask ("Stencil Read Mask", Float) = 255

		[HideInInspector] _ColorMask ("Color Mask", Float) = 15

		[Toggle(UNITY_UI_ALPHACLIP)] _UseUIAlphaClip ("Use Alpha Clip", Float) = 0

		// Outline properties are drawn via custom editor.
		[HideInInspector] _OutlineWidth("Outline Width", Range(0,8)) = 3.0
		[HideInInspector] _OutlineColor("Outline Color", Color) = (1,1,0,1)
		[HideInInspector] _OutlineReferenceTexWidth("Reference Texture Width", Int) = 1024
		[HideInInspector] _ThresholdEnd("Outline Threshold", Range(0,1)) = 0.25
		[HideInInspector] _OutlineSmoothness("Outline Smoothness", Range(0,1)) = 1.0
		[HideInInspector][MaterialToggle(_USE8NEIGHBOURHOOD_ON)] _Use8Neighbourhood("Sample 8 Neighbours", Float) = 1
		[HideInInspector] _OutlineOpaqueAlpha("Opaque Alpha", Range(0,1)) = 1.0
		[HideInInspector] _OutlineMipLevel("Outline Mip Level", Range(0,3)) = 0
	}

	SubShader
	{
		Tags
		{
			"Queue"="Transparent"
			"IgnoreProjector"="True"
			"RenderType"="Transparent"
			"PreviewType"="Plane"
			"CanUseSpriteAtlas"="True"
		}

		Stencil
		{
			Ref [_Stencil]
			Comp [_StencilComp]
			Pass [_StencilOp]
			ReadMask [_StencilReadMask]
			WriteMask [_StencilWriteMask]
		}

		Cull Off
		Lighting Off
		ZWrite Off
		ZTest [unity_GUIZTestMode]
		Fog { Mode Off }
		Blend One OneMinusSrcAlpha
		ColorMask [_ColorMask]

		Pass
		{
			Name "Normal"

		CGPROGRAM
			#pragma shader_feature _ _STRAIGHT_ALPHA_INPUT
			#pragma shader_feature _ _CANVAS_GROUP_COMPATIBLE
			#pragma vertex vert
			#pragma fragment frag
			#pragma target 2.0

			#include "CGIncludes/Spine-SkeletonGraphic-NormalPass.cginc"
			#include "Packages/com.coffee.softmask-for-ugui/Shaders/SoftMask.cginc"
			#pragma shader_feature_local _ SOFTMASK_EDITOR
			#pragma shader_feature_local _ SOFTMASKABLE

			struct v2f
            {
                float4 vertex   : SV_POSITION;
                fixed4 color    : COLOR;
                float2 texcoord  : TEXCOORD0;
                float4 worldPosition : TEXCOORD1;
                float4  mask : TEXCOORD2;
                UNITY_VERTEX_OUTPUT_STEREO
            };

			fixed4 frag(v2f IN) : SV_Target
			{
				half4 color = IN.color * (tex2D(_MainTex, IN.texcoord) + _TextureSampleAdd);
				
				color.a *= SoftMask(IN.vertex, IN.worldPosition, color.a);
				return color;
			}
		ENDCG
		}
	}
	CustomEditor "SpineShaderWithOutlineGUI"
}
`

So I don't know if I did it right (probably not), and it says:
`
Metal: Error creating pipeline state (Spine/SkeletonGraphic (SoftMaskable)): Fragment input(s) `user(TEXCOORD0)` mismatching vertex shader output type(s) or not written by vertex shader
(null)
`

did you tried it?

**Comment by mob-sakai** [comment]
Sorry, I misunderstood Spine.  
Spine renders by stacking multiple meshes.  
Simple softness processing causes "see-through" when semi-transparent objects overlap.

<img width="320" alt="image" src="https://github.com/user-attachments/assets/e62ef529-f9b0-4586-8b74-738b9b3fd450" /> <img width="320" alt="image" src="https://github.com/user-attachments/assets/4a01b32b-85cf-4474-8d3a-c37b0e7df76c" />

**Comment by mob-sakai** [comment]
I made this: [Spine-SkeletonGraphic-SoftMaskable.shader.zip](https://github.com/user-attachments/files/18216717/Spine-SkeletonGraphic-SoftMaskable.shader.zip)

**Comment by mob-sakai** [comment]
Official document: https://esotericsoftware.com/spine-unity-rendering#Fading-a-Skeleton-In-or-Out

**Comment by Schrodinger123** [comment]
> I made this: [Spine-SkeletonGraphic-SoftMaskable.shader.zip](https://github.com/user-attachments/files/18216717/Spine-SkeletonGraphic-SoftMaskable.shader.zip)

Wow! This totally solved it.
Thanks a lot!

**Comment by mob-sakai** [comment]
NOTE: Add the shaders as a sample in near feature.
