### ISSUE TITLE
How to create highlight area?

### ISSUE THREAD

**Issue by Tetromiko** [mob-sakai/SoftMaskForUGUI#220]
I want to create an FTUE for a project I'm working on, and a highlight area is part of it. The area consists of two parts: a full-screen shadow that covers all UI elements and a light spot that can move to any position. How can I implement the logic so that the shadow blocks all interactions with the UI, while the light spot allows interactions with the interface?

**Comment by mob-sakai** [comment]
Tell me about your develop/build environment.
 - version [e.g. 3.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2022.2.0f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP/HDRP]

Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
Of course, you don't need to include any secret assets from your project. Feel free to use free assets instead.

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by Tetromiko** [comment]
There is nothing to share. I'm creating this logic in a separate clean project on version 2021.3.33f for Android. It is not an issue; I'm just asking if it is possible to achieve my goal, and if the answer is yes, how can I make it?

**Comment by mob-sakai** [comment]
Okay.
That is a common question I ask, and sharing prerequisites is important for providing accurate responses.
For instance, depending on your environment or implementation method, a different approach might be more appropriate.

- Are the button and the black screen on the same canvas?  
- Is the canvas RenderMode set to ScreenSpaceOverlay or ScreenSpaceCamera?  
- What is the clip shape: rectangular, circular, or star-shaped?  
- Does the clip shape require softness?

This time, I respond assuming a general case:  

- Use a tutorial-specific canvas (ScreenSpaceOverlay).  
- The clip shape is rectangular (non-softness).  

---

![](https://github.com/user-attachments/assets/6a971eb8-f8b3-4524-892e-76b989b444e5)

See "Sample: Tutorial Button" in the demo scene.
The button underneath the black screen is not interactable, but the part clipped by `MaskingShape` component (subtractive method) is interactable.

---

[TutorialSample.unity.zip](https://github.com/user-attachments/files/18216863/TutorialSample.unity.zip)
![](https://github.com/user-attachments/assets/50dbaf19-7502-45ff-84f2-7f7f7505b528)

This scene is a simplified version of the tutorial, containing 2 buttons and a black screen.
![](https://github.com/user-attachments/assets/1ebc0271-3468-40bf-a6b0-fdd6f5f65f41)

The clipping area is defined by "MaskingShape - Subtract" and follows the button using the RectTransformFitter component.
![](https://github.com/user-attachments/assets/126c713b-92d0-41dc-bfa0-0e3a545cf62d)

**Comment by Tetromiko** [comment]
_Are the button and the black screen on the same canvas?_ - Yes
_Is the canvas RenderMode set to ScreenSpaceOverlay or ScreenSpaceCamera?_ - ScreenSpaceOverlay 
What is the clip shape: rectangular, circular, or star-shaped? - It is a image with blured circle
Does the clip shape require softness? - Yes

![image](https://github.com/user-attachments/assets/19979e46-c42c-4f3b-ae6c-eab2be0b3d79)
![image](https://github.com/user-attachments/assets/d1741180-615c-4a72-8e64-438869b6a725)

**Comment by mob-sakai** [comment]
Can you submit a minimal project, scene, or prefab?
Images, assets, or scripts that cannot be submitted are not necessary.

**Comment by Tetromiko** [comment]
The screen is completely covered with a shadow, but there is one area where the shadow is “removed” using the Subtract mask. In the shaded area, clicks should be blocked, and in the lightened area, they should be allowed. It's important that this highlighted area can move freely on the screen. Is this functionality supported by the library? If so, how can I implement it correctly?

**Comment by Tetromiko** [comment]
We have a Canvas containing some buttons. On the same Canvas, there is a Mask with two children: a shadow mask in "Add" mode and a light spot in "Subtract" mode. When I try to click on the subtracted area, the buttons underneath are not responsive, as if the Mask is intercepting the input.

**Comment by mob-sakai** [comment]
I cannot guess which components are attached to which objects.

For accuracy in the response, please compress the prefab into a zip file and attach it as a comment.
There’s no need to include images or other assets.

Additionally, as a helpful tip, the EventSystem inspector can show which object the raycast hit.  
This is also a crucial piece of information.

---

Now, I noticed that the SoftMask component is blocking raycasts for the MaskingShape (Subtract) component.
This is a bug and will be fixed ASAP. :+1:

**Comment by Tetromiko** [comment]
Thank you, you are doing a great job, But when it will be possible to download through git link?
