### ISSUE TITLE
Material UI/Default-SoftMask doesn't have _Stencil property

### ISSUE THREAD

**Issue by caneva20** [mob-sakai/SoftMaskForUGUI#26]
It started happening after tweaking some settings on the mask, and now I can't get it to work again, it is drawing just a pink rectangle.

Edit: I've fixed that by closing the project and deleting the "Library" folder.
Edit2: I'm using Unity 2018.3.1f1

**Comment by mob-sakai** [comment]
Hi @caneva20 
Thank you for reporting.

**Comment by mob-sakai** [comment]
I've been there before.
It happened with (standard) Mask component too, but it is difficult to reproduce.

**Comment by caneva20** [comment]
I tried to reproduce it again, and no "luck"
I'll let you know if that happens again, and try to find a pattern.
