### ISSUE TITLE
Does not work with flipped/rotated images

### ISSUE THREAD

**Issue by caneva20** [mob-sakai/SoftMaskForUGUI#27]
If you rotate the image object (eg. 180º) the mask stops working.

I've tried to use another asset to flip the image, and the same happens.

**Comment by mob-sakai** [comment]
Hi  @caneva20 
Thank you for reporting.

**Comment by mob-sakai** [comment]
I would like to know more information on this issue.
Can you submit a reproducible project for this issue?

**Comment by mob-sakai** [comment]
This issue was reproduced in my environment.
Adding `Cull Off` to SoftMask.shader fixed this issue.
