### ISSUE TITLE
Soft Maskeable is NOT masked by Unity's Mask

### ISSUE THREAD

**Issue by caneva20** [mob-sakai/SoftMaskForUGUI#28]
![ingame](https://user-images.githubusercontent.com/9308435/51704591-93024880-2000-11e9-9f9f-31023dc6a988.PNG)

As I hope you can see and undestand, GUI elements with SoftMaskeable is not masked by Unity's mask.
In the print I'm using a ScrollView

**Comment by caneva20** [comment]
Maybe this one is better
![capture](https://user-images.githubusercontent.com/9308435/51705057-b8dc1d00-2001-11e9-976f-361871ee95f5.PNG)

**Comment by mob-sakai** [comment]
Hi @caneva20 
Thank you for reporting.

**Comment by mob-sakai** [comment]
Can you submit a reproducible project for this issue?

**Comment by mob-sakai** [comment]
Hmm...
You use RectMask2D, right?

**Comment by caneva20** [comment]
First off, I'm really sorry. I thought I've given enough info, but reading it now I see I gave you almost nothing :)

I'm using UI>ScrollView (Unity's Default) 

> You use RectMask2D, right?
Nope

I have a simple demo project with the issue. (Unity 2018.3.1f1)
[SoftMaskIssueDemo.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/2796183/SoftMaskIssueDemo.zip)

**Comment by mob-sakai** [comment]
Thank you for uploading the project.

However, sorry, I do not know how to check your scene...
This scene does not seem to include SoftMask and SoftMaskable.
Some missing components are included.

**Comment by caneva20** [comment]
Whoops, Unity lost some references when I removed the Library folder.

Try this one (is a .unitypackage): [SoftMaskIssueDemo.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/2796249/SoftMaskIssueDemo.zip)

**Comment by mob-sakai** [comment]
OK, the issue was reproduced.
![](https://user-images.githubusercontent.com/12690315/51750209-b3133400-20f4-11e9-899a-4e9742c96582.png)


If you want to solve this issue quickly, change Viewport's Mask to RectMask2D.
And import this unitypackage: [fix.unitypackage.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/2796378/fix.unitypackage.zip)

**Comment by caneva20** [comment]
Changing to RectMask2D fixed the issue, BUT the package is not needed and actually "broke" my mask

BEFORE:
![capture](https://user-images.githubusercontent.com/9308435/51750859-71559f80-209a-11e9-8822-3439122af473.PNG)

AFTER:

![capture](https://user-images.githubusercontent.com/9308435/51750818-5420d100-209a-11e9-8c11-6b8b995ce934.PNG)

**Comment by mob-sakai** [comment]
Oh, sorry.

**Comment by caneva20** [comment]
No problem, I just "reolled back" the shaders

**Comment by mob-sakai** [comment]
To fix the issue with Mask component, I will add mask interaction for each mask layers.

**Comment by caneva20** [comment]
All the files have a different GUID indeed, but I honestly don't know why.

The only thing a remember was having an issue the first time I exported the project, but that should not change GUIDs. I've tried to "reproduce" what happened here, but no luck. or maybe it happened when I was messing around with the package manager...
