### ISSUE TITLE
if canvas camera is not set in world space mode, masked contents are not displayed

### ISSUE THREAD

**Issue by drdavient** [mob-sakai/SoftMaskForUGUI#36]
**Describe the bug**
1. When a worldspace camera is used (rather than screen overlay). The Masked content will reduce in width, height as it approaches (0,0)

2. If worldspace / screenspace camera are chosen and the camera is set in the canvas. The Mask will display nothing. 

**To Reproduce**
1. Import package attached into project with SofMaskForUGUI installed
2, Check Scene is working Should see UnityChan SoftMasked in a Star
3. Move Canvas down and or Left
4. Unity Chan is cropped as approaching (0,0)
[PositionBug.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/2945949/PositionBug.zip)

**Environment (please complete the following information):**
 - Platform Editor (Windows 10 (x64))
 - Unity: [e.g. 2018.3.7f1
 - SoftMaskForUGUI: [e.g. v0.6.0]

**Additional context**
Add any other context, screenshots or gif animations about the bug here.

**Comment by mob-sakai** [comment]
Hi @drdavient 
Thank you for reporting!

**Comment by mob-sakai** [comment]
Hmm...
I don't understand completely what you mean...

When I load your scene, the "star" mask is flipped, right?
![](https://user-images.githubusercontent.com/12690315/54100370-76c83880-4401-11e9-86aa-8f0aa35fdf27.png)

**Comment by drdavient** [comment]
Your fix to flipping the object is a good one :) (Not what I was reporting though :)

Your scene view observations are correct - though I also get this in the game view. I'm showing this in the attached image. 
![image](https://user-images.githubusercontent.com/4351544/54117902-bd119d80-43e9-11e9-837f-237d5b6bd6cc.png)

And new demo project (using 0.7.0 now)
[SoftMaskCropping.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/2951784/SoftMaskCropping.zip)

**Comment by mob-sakai** [comment]
Thank you very much. 👍
It was really easy to understand and to fix!
![](https://user-images.githubusercontent.com/12690315/54120567-5ddc7900-443b-11e9-8c75-91c29598066e.gif)

I'll release a fixed version, ASAP. :)
