### ISSUE TITLE
Doesn't work with Screen-Space Overlay

### ISSUE THREAD

**Issue by itsagam** [mob-sakai/SoftMaskForUGUI#41]
Doesn't work in "Screen Space - Overlay" (shows correctly in the Editor but does not work in-game).

1. Play the included demo.
2. Scroll to bottom and switch to "Overlay".
3. Scroll up and notice.

 - Platform: Windows/Editor
 - Unity: 2018.3.8
 - SoftMaskForUGUI: v0.7.1

![Capture](https://user-images.githubusercontent.com/5146415/54321144-97ff7380-4611-11e9-8f52-09ce72f435fc.PNG)
![Capture1](https://user-images.githubusercontent.com/5146415/54321148-9c2b9100-4611-11e9-919e-07993fa07047.PNG)

**Comment by mob-sakai** [comment]
Hi @itsagam 
Thsnk you for reporting!

Hmm, It does not work correctly on game view in editor, right?

**Comment by itsagam** [comment]
Indeed, I saw there were previous issues with Overlay but they were closed. Not sure what’s hapenning. Thank you for making your work available though.

**Comment by mob-sakai** [comment]
Okay, I'll fix it as soon as possible.
Thank you again!

**Comment by mob-sakai** [comment]
Please try v0.7.2

**Comment by itsagam** [comment]
Okay, I tested it. It works in Screen-Space Overlay mode now, but the code changes introduced a regression where it doesn't work as intended in Screen-Space Camera and World Space. The masked image is offset by viewing position (see screenshots).

This is just to report. I bought an package from Asset Store that got the job done. Thanks!
 
![Capture1](https://user-images.githubusercontent.com/5146415/54389248-7a89e280-46c1-11e9-8a52-e022de17725d.PNG)
![Capture](https://user-images.githubusercontent.com/5146415/54389261-7d84d300-46c1-11e9-9dcd-885efd2935e6.PNG)

**Comment by mob-sakai** [comment]
Thank you for testing. :)
For the time being, we have discontinued the v0.7.2 release.
I will continue to fix.

**Comment by mob-sakai** [comment]
Hi @itsagam 
Can you test this?
[fixed.unitypackage.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/2971838/fixed.unitypackage.zip)

If there is no bug, I will release v0.7.2. :)

**Comment by itsagam** [comment]
Sure, sure. Okay, so, the asset works now in all three modes (Screen-Space Overlay, Screen-Space Camera, World Space), but while testing it thoroughly, I encountered two more bugs:

1) If you maximize Game View (either with "Game -> Right-click -> Maximize" or "Maximize on Play"), the masked images all disappear. 
![image](https://user-images.githubusercontent.com/5146415/54467371-83081900-47a6-11e9-9c3c-efce40f41d57.png)

2) Intermittently, get "Attempting to ReadPixels outside of RenderTexture bounds! Reading .... from ...." errors.
![image](https://user-images.githubusercontent.com/5146415/54467414-c6628780-47a6-11e9-9960-c764ec5db1ae.png)

I had the package from v0.7.1, so I installed it again to see whether these were a regression, but they happen there as well and seem to be unrelated to the changes you made. I wish I could help you diagnose any of it, but shader programming is not my forte. Do let me know, however, if you ever need some help with editor scripting side of things.

Best.

**Comment by itsagam** [comment]
Reading the exception now, maybe it is an off-by-one error? Trying to read pixel 289 from size 288? Just a thought, I'm a noob with shaders.

**Comment by mob-sakai** [comment]
Many thanks!
And, 3. the masked image disappears when the game view is resized.

Actually, the bugs are independent.
I created new issues for the bugs and fixed them!
#42, #43, #44

**Comment by mob-sakai** [comment]
Please try this
[fixed_2.unitypackage.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/2973810/fixed_2.unitypackage.zip)

**Comment by mob-sakai** [comment]
Thank you for your cooperation! :+1: 
I'll release it.
