### ISSUE TITLE
SoftMask at wrong position

### ISSUE THREAD

**Issue by buihuuloc** [mob-sakai/SoftMaskForUGUI#45]
I am using the newest SoftMask version

**Comment by mob-sakai** [comment]
Hi @buihuuloc 

Tell me more information of your project.
And, can you submit a screenshot?

**Comment by buihuuloc** [comment]
It only happens on Android.
It works perfectly on iOS. :(

**Comment by buihuuloc** [comment]
I sent you a video via email

**Comment by lvictorino** [comment]
Hey there. I don't know if this one has been solved but I think I encountered the same issue. The mask is perfectly fine in Scene view while a tiny offset is visible in Game view. Any idea on what I missed here?

![image](https://user-images.githubusercontent.com/18822/54928136-bfa8e280-4f13-11e9-9148-62503a406aa9.png)

**Comment by mob-sakai** [comment]
Hi @lvictorino 
Can you submit a small project that can reproduce the issue?

**Comment by mob-sakai** [comment]
Does the issue also occur in player builds?

**Comment by lvictorino** [comment]
Hey @mob-sakai while trying to reproduce it in a fresh project, I found the issue. My canvases are all contained in an empty GameObject. That object had a very small offset that was, somehow, applied to the mask position even if the canvas containing the mask is defined as screen overlay. Removing that offset in the parent GameObject fixed it. Sorry for the useless question. I hope it helps.

**Comment by mob-sakai** [comment]
@lvictorino 
Thanks!

**Comment by mob-sakai** [comment]
@lvictorino 
Please submit a project that can reproduce the issue just in case. :)

**Comment by lvictorino** [comment]
Here you go. The top object (the one that contains the canvas) is messing everything. If you change the position to zero, everything is back to normal.

![image](https://user-images.githubusercontent.com/18822/54988908-b2453400-4fb7-11e9-948c-ebb1c234a7af.png)


[softmask-test.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/3007588/softmask-test.zip)

**Comment by mob-sakai** [comment]
Thanks to your help, the bug will be fixed. :)
![image](https://user-images.githubusercontent.com/12690315/54992684-3bce2380-5003-11e9-9598-ea67218ae620.png)

**Comment by mob-sakai** [comment]
@lvictorino 
Thanks to your help, the bug will be fixed. :)
![image](https://user-images.githubusercontent.com/12690315/54992684-3bce2380-5003-11e9-9598-ea67218ae620.png)

**Comment by lvictorino** [comment]
awesome thanks!
