### ISSUE TITLE
The masked images all disappear when the screen orientation is changed

### ISSUE THREAD

**Issue by laicasaane** [mob-sakai/SoftMaskForUGUI#46]
**Describe the bug**
When the screen orientation is changed from Portrait to Landscape and vice versa, all images disappeared.

**Environment (please complete the following information):**
 - Platform: Editor(Windows), Android
 - Unity: 2018.3.8f1
 - SoftMaskForUGUI: v0.7.2

**Comment by laicasaane** [comment]
It's weird. That's happened when I used PackageManager to install SoftMask, even your demo scene wouldn't work. And that was 2 days ago. But now I download the .unitypackage and import it to my project, your demo works perfectly.

**Comment by mob-sakai** [comment]
Oh, sorry to confuse you!
In fact, v0.7.2 was released by mistake.

**Comment by mob-sakai** [comment]
I discontinued v0.7.2 release and fixed it.
And then, I released it 'correctly'.

**Comment by laicasaane** [comment]
Wow! It works perfectly now. ❤️
