### ISSUE TITLE
Camera movement affects the mask rendering when on a World Space Canvas.

### ISSUE THREAD

**Issue by DiegoGal** [mob-sakai/SoftMaskForUGUI#49]
Hi there!

I have a camera with a script that moves his transform position at update. When playing the game, the camera starts moving the SoftMask  instead of letting  it at his place, as I show you right here:

![Orto1conv](https://user-images.githubusercontent.com/3625771/56805959-d603d000-682a-11e9-8e61-270381e9ef8e.gif)

The masked element is on a Canvas with World Space render mode. But furthermore, if I check the maskable element to use Stencil, the movement only applies to the maskable item, the mask stands where I want it.

![Orto2](https://user-images.githubusercontent.com/3625771/56806349-f8e2b400-682b-11e9-95cb-aeacdbc9d05b.gif)

The camera is Orthographic and the hierarchy of the objects is as follows:

![image](https://user-images.githubusercontent.com/3625771/56806483-5414a680-682c-11e9-8479-252b2a1ac4f2.png)

The behaviour I want is the mask to stay at its place on the real world and not being influenced by the camera movement.

Specs:
 - Platform: Windows 10
 - Unity: [e.g. 2018.2.12f1]
 - SoftMaskForUGUI: v0.7.2

If you want to see some of the code of how I move the camera or some other configurations just ask for it, I will be pleased to show you :)

Despite that, I love the plug-in, great work! 💃

**Comment by mob-sakai** [comment]
Hi @DiegoGal 
Thank you for reporting. :)

I would like to know more information on this issue.
Can you submit a small reproducible project for this issue?

**Comment by DiegoGal** [comment]
Of course!

Here you are, the camera movement is randomized each time and moves very smoothly, but you can move camera to see tha the mask goes away its original position.

[KillerPunk.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/3121760/KillerPunk.zip)

**Comment by mob-sakai** [comment]
Thanks!

**Comment by mob-sakai** [comment]
@DiegoGal 

WIP: When moving the world camera, `hasChanged` flag was not set to true.

**Before**
![before](https://user-images.githubusercontent.com/12690315/56881764-67c64400-6a9c-11e9-9ec7-60302d697628.gif)

**After**
![after](https://user-images.githubusercontent.com/12690315/56881769-6d238e80-6a9c-11e9-85f0-c41f84428dcb.gif)

**Comment by DiegoGal** [comment]
Wow! That is just what I need, where is the best place to change that?

**Comment by mob-sakai** [comment]
When the camera moves (when the camera view matrix or projection matrix changes), hasChanged should be true.

**SoftMask.cs**
```
static void UpdateMaskTextures()
{
	s_nowViewProjectionMatrices.Clear ();
	foreach (var sm in s_ActiveSoftMasks)
	{
		if (!sm || sm._hasChanged)
			continue;
        
        // ADD FROM HERE
		var canvas = sm.graphic.canvas;
		if (canvas.renderMode == RenderMode.WorldSpace)
		{
			var cam = canvas.worldCamera;
			Matrix4x4 nowsVP = cam.projectionMatrix * cam.worldToCameraMatrix;
			Matrix4x4 previousVP = cam.reviousViewProjectionMatrix;

            s_nowViewProjectionMatrices.
            if (previousVP != nowsVP)
            {
                sm.hasChanged = true;
            }
        }
        // TO HERE

        var rt = sm.rectTransform;
        if (rt.hasChanged)
        {
            rt.hasChanged = false;
            sm.hasChanged = true;
        }
...
```

**Comment by mob-sakai** [comment]
Note: `Camera.reviousViewProjectionMatrix` property has been added in Unity 2018.1.

**Comment by mob-sakai** [comment]
This will be released soon.

**Comment by AndreasMLarsen** [comment]
I was just doing some testing and it seems the previous projection matrix and the current projection matrix are never the same if the camera is still, causing hasChanged to always be set to true

**Comment by mob-sakai** [comment]
@AndreasMLarsen 

Wow.
Please create an issue about that.
