### ISSUE TITLE
Unity 2018.x compile failed

### ISSUE THREAD

**Issue by CHFreezer** [mob-sakai/SoftMaskForUGUI#51]
Assets\Coffee\UIExtensions\SoftMaskForUGUI\Scripts\SoftMask.cs(417,33): error CS1061: 'Camera' does not contain a definition for 'reviousViewProjectionMatrix' and no accessible extension method 'reviousViewProjectionMatrix' accepting a first argument of type 'Camera' could be found (are you missing a using directive or an assembly reference?)

https://github.com/mob-sakai/SoftMaskForUGUI/blob/bffaed3d78257edcb0f50562eae3fb6933e98010/Assets/Coffee/UIExtensions/SoftMaskForUGUI/Scripts/SoftMask.cs#L417
modify to:
`    Matrix4x4 previousVP = cam.previousViewProjectionMatrix;`

**Comment by mob-sakai** [comment]
Hi @CHFreezer 
Thank you for your reporting!
