### ISSUE TITLE
Raycast coordinates are incorrect

### ISSUE THREAD

**Issue by CHFreezer** [mob-sakai/SoftMaskForUGUI#52]
Masked button can't be clicked.

 - Unity: 2019.1.1f1
 - SoftMaskForUGUI: v0.8.0

I tried to modify
https://github.com/mob-sakai/SoftMaskForUGUI/blob/bffaed3d78257edcb0f50562eae3fb6933e98010/Assets/Coffee/UIExtensions/SoftMaskForUGUI/Scripts/SoftMask.cs#L243
to:
`    int y = (int)((softMaskBuffer.height - 1) * (1 - Mathf.Clamp01(sp.y / Screen.height)));`
after it worked for me.
But I want to know why, thanks!

**Comment by mob-sakai** [comment]
Hi @CHFreezer 
Thank you for reporting!

* Can you submit a reproducible project for this issue?
* Please tell me your environment
  * Platforms: e.g. Editor [Windows/Mac], Standalone [Windows/Mac], iOS, Android, etc...
  * Devices:
  * GPU and Graphic API:

**Comment by mob-sakai** [comment]
I think UNITY_UV_STARTS_AT_TOP is related.

**Comment by vekstr** [comment]
@CHFreezer 's fix also worked for me

**Comment by boloyo** [comment]
> I think UNITY_UV_STARTS_AT_TOP is related.

Yes, it is. OpenGL works fine, but DX11 has this problem.

**Comment by mob-sakai** [comment]
I am sorry for not fixing this problem for a long time.
I will fix it with `SystemInfo.graphicsUVStartsAtTop` API.

https://docs.unity3d.com/2017.4/Documentation/ScriptReference/SystemInfo-graphicsUVStartsAtTop.html
