### ISSUE TITLE
Wrong masking with resolution change (WorldSpace Canvas)

### ISSUE THREAD

**Issue by AGM-GR** [mob-sakai/SoftMaskForUGUI#54]
A canvas in World Space and only a simple ScrollView with a softmask viewport. At changing resolution the mask go wrong until some change in canvas elements.
It seems like this element not being reconstruct at resolution change.

 - Platform: WebGL
 - Unity: 2018.3.0f2
 - SoftMaskForUGUI: v0.8.1

![sm1](https://user-images.githubusercontent.com/9071269/57538367-8fdd5f00-7348-11e9-86ea-edb859426faa.png)
![sm2](https://user-images.githubusercontent.com/9071269/57538370-91a72280-7348-11e9-8861-b3cd398eb5f0.png)

**Comment by mob-sakai** [comment]
Hi @AGM-GR 
Thank you for your reporting!

**Comment by mob-sakai** [comment]
@AGM-GR 
Can you submit a reproducible minimum project for this issue?

**Comment by AGM-GR** [comment]
There's no bug in this package. I don't know why when I tried to update this package in my project my cloud storage manager replaced it again with the old version. It's work nice now I had fixed it in my project.
Sorry for the useless issue I created and thanks for this amazing package!
