### ISSUE TITLE
Prefab Mode in Play Mode is not supported

### ISSUE THREAD

**Issue by strawlink** [mob-sakai/SoftMaskForUGUI#60]
**Describe the bug**
The following message appears when entering play mode while having a prefab open. The prefab edit mode is then stopped and you're thrown back to the scene.

```
Prefab Mode in Play Mode was blocked by the script 'SoftMaskable' to prevent the script accidentally affecting Play Mode. See the documentation for [ExecuteInEditMode] and [ExecuteAlways] for info on how to make scripts compatible with Prefab Mode during Play Mode.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**To Reproduce**
1. Create a prefab.
2. Add the SoftMaskable script to any object inside it.
3. Open the prefab in prefab editing mode.
4. Start Play-mode.
5. Observe that prefab editing mode is stopped.

**Environment (please complete the following information):**
 - Platform: Editor (Windows)
 - Unity: 2019.2.1f1
 - SoftMaskForUGUI: 0.8.1

**Additional context**
By changing the ExecuteInEditMode attribute to ExecuteAlways, the warning is removed and the Prefab Edit mode stays open - I do not know if there are any unintentional changes due to this, so I figured it was best to make a bug report.

**Comment by mob-sakai** [comment]
Hi @strawlink 
Thank you for your reporting!

**Comment by AlexD182** [comment]
Repeated in Unity 2020.3.30f1
