### ISSUE TITLE
Raycast outside of visible area

### ISSUE THREAD

**Issue by bourgeoismaxime** [mob-sakai/SoftMaskForUGUI#61]
Hello,
I started using the plugin yesterday to put soft masks on scrollview.
It seems like raycast are hitting the UI elements inside the hidden part of the scrollview

Here is how my setup looks like :
![Problem](https://user-images.githubusercontent.com/11771615/64448724-59bcab80-d0ac-11e9-8937-58f1c5156e2e.png)
![Problem2](https://user-images.githubusercontent.com/11771615/64452358-3695fa00-d0b4-11e9-8425-9e5b22230847.png)
There is a huge text inside of a scrollview. The scrollview has a soft mask and the text is correctly masked when scrolled. 
At the beginning when the scrollview isn't scrolled at all, I can press the button. However, when I scroll, the hidden text goes above the button and prevents me from clicking on it.
The text is a TextMeshPro component but I have the same problem with anything interactable I put in the scrollview with the raycast target enabled.
Camera is in Orthographic, Canvas is in "Screen Space - Camera".

I created a repro project but it worked perfectly on it. I don't know what in my project causes the hidden element to still be interactable.
Is there anything I have to add or set to have the raycast working only on the visible part ?

**Environment (please complete the following information):**
 - Platform: Editor(Windows)
 - Unity: 2018.3.7f1
 - SoftMaskForUGUI: v0.9.0

**Comment by mob-sakai** [comment]
Hi @bourgeoismaxime 
Thank you for your reporting!

**Comment by bourgeoismaxime** [comment]
Hello, 
I have found a workaround but haven't gotten deep enough in the debugging to understand why.
My current solution is to place an image without sprite and a soft maskable on the viewport gameobject. With the image plus the soft maskable, it becomes impossible for me to scroll by clicking on the masked text.

Issue is that I still cannot reproduce that in the repro project maybe because it is too simple.

**Comment by YenYaoHan** [comment]
add rect mask 2d into your scroller ,it would be helpful.

![image](https://user-images.githubusercontent.com/17308097/83217365-2c65df80-a19e-11ea-979b-4abf86353ba6.png)

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
If the same issue arises, please re-open this issue.
