### ISSUE TITLE
Update softmask not working when canvas component was deactivated

### ISSUE THREAD

**Issue by Danilovic** [mob-sakai/SoftMaskForUGUI#66]
Hi!

I have encountered an issue when I deactivate the canvas component of a gameobject where the masks are located, when softmask script tries to update those masks, it throws a null.

You can find a little package with an example.

[SoftMaskIssue.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/3891971/SoftMaskIssue.zip)

Regards

**Comment by mob-sakai** [comment]
Hi @Danilovic 

Thank you for your reporting!

**Comment by mob-sakai** [comment]
@Danilovic 

Many scripts are missing in your scene... X(
Please zip your entire project folder and attach it.

![image](https://user-images.githubusercontent.com/12690315/69960542-11971300-154d-11ea-9ea0-2af83993d463.png)

**Comment by Danilovic** [comment]
@mob-sakai 

I just downloaded the package in another pc with a clean Unity with no projects and I didn't see the missing files, in fact, I didn't use any custom script for this example. Could you show me the gameobject (s) with this problem?

**Comment by mob-sakai** [comment]
@Danilovic 

I imported it to Unity2018.3 project on Mac.
I will try again with a clean project.
Thanks!

**Comment by mob-sakai** [comment]
@Danilovic

Hmm, I tested it with Unity2018.2 and Unity2018.3 on Mac and Windows, but it does not work...
So, I fixed `m_Script` in scene file.
I will test it later. :)

**Comment by mob-sakai** [comment]
@Danilovic 

Fix SoftMask.cs(line:428) as following:
```cs
if (!sm || sm._hasChanged)
```
To
```cs
if (!sm || sm._hasChanged || !sm.graphic || !sm.graphic.canvas)
```

Does it work well?

**Comment by Danilovic** [comment]
@mob-sakai 

It doesn't work for me. I tested the package on Unity 2019.2.8 and works ok, without missing scripts so I tested the same package on Unity 2018.2 and I saw the missing files. Please check on Unity 2019.2.8

**Comment by JJarvis89** [comment]
Hi, I am having the same issue.

Attached you can find a sample project (hopefully with no missing scripts!)

Steps:
1. Open SampleScene
2. Run
3. Disable Canvas

This causes a NullReferenceException. Depending on which Canvas Render mode the culprit is either the Canvas or the Camera.

Kind regards
[SoftMaskIssue.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/4117790/SoftMaskIssue.zip)

**Comment by mob-sakai** [comment]
@JJarvis89 , @Danilovic 

Thank you!
I will fix it ASAP.
