### ISSUE TITLE
Not working in Unity 2018.4.18f1 but works fine with 2018.4.16 or below

### ISSUE THREAD

**Issue by teh1archon** [mob-sakai/SoftMaskForUGUI#70]
I get the following error when firing up the project on 2018.4.18:

> Shader error in 'UI/Default-SoftMask': failed to open source file: './../../SoftMask.cginc' at line 60 (on d3d11)
> Compiling Vertex program with SOFTMASK_EDITOR
> Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING

Happens 100% of the time in 2018.4.18 but never happening in 2018.4.16. I have not checked with .17.

I also get:
> Capture has no panel, forcing removal (capture=TemplateContainer  (x:0.00, y:0.00, width:270.00, height:23.00) world rect: (x:0.00, y:158.00, width:270.00, height:23.00) eventType=null)

Not sure if it's part of it, or not.

**Environment:**
 - Platform: [Editor(Windows), iOS, Android, WebGL]
 - Unity: [e.g. 2018.4.18f1]
 - SoftMaskForUGUI: [v0.9.1]

**Additional Info:**
I'm also using yours UIEffect in the project but I highly doubt it has anything to do with it.

**Comment by mob-sakai** [comment]
@teh1archon 
Sorry for my late reply.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
If the same issue arises, please re-open this issue.
