### ISSUE TITLE
Image with UI-Default-SoftMask.shader could not cover other image behind of it.

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [mob-sakai/SoftMaskForUGUI#72]
**Describe the bug**
Image with UI-Default-SoftMask.shader could not cover other image behind of it.

**Environment (please complete the following information):**
 - Platform: Editor Windows,  Android
 - Unity: 2019.2.1f1
 - SoftMaskForUGUI: 1.9.1

**Comment by mob-sakai** [comment]
@BelieveXiaoShuai 
I would like to know more information on this issue.
Can you attach a minimal repro project for this issue?
