### ISSUE TITLE
Softmask not working on PS4

### ISSUE THREAD

**Issue by Danilovic** [mob-sakai/SoftMaskForUGUI#74]
Hi, 

it seems that softmask has errors in a concrete shader in Playstation 4 (currently working fine on PC and Nintendo Switch). With this error, objects with softmask are shown with pink material.

This is the log from the console:
WARNING: Shader Unsupported: 'UI/Default-SoftMask' - Pass 'Default' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'UI/Default-SoftMask' - Setting to default shader.

Environment:
 - Platform: [Playstation 4]
 - Unity: [2019.3.0f6]
 - SoftMaskForUGUI: [v0.9.1]

Regards,

**Comment by mob-sakai** [comment]
@Danilovic 
Hmm, please try to comment this line.
https://github.com/mob-sakai/SoftMaskForUGUI/blob/f89df67e865eeb29d47864843f6c718f66563eb7/Assets/Coffee/UIExtensions/SoftMaskForUGUI/Shaders/Resources/UI-Default-SoftMask.shader#L52
