### ISSUE TITLE
TextMeshPro Material keeps resetting itself to non-masked version

### ISSUE THREAD

**Issue by MartinHaeusler** [mob-sakai/SoftMaskForUGUI#75]
Hi,
I'm using your Soft Mask asset and I'm trying to apply it to a scroll view. Inside, there's some panels and some text rendered with TextMeshPro.

Your editor addon kindly suggests to change the material of the font assets to be the "Distance Field (Soft Maskable)" version. Klicking on "fix" also works.

However, when I try to apply this on a prefab, and then instantiate the prefab, the material of the TextMeshPro assets will always **reset itself to the TMP shader**, instead of the soft mask shader.

Is there anything I can do about this?

**Environment (please complete the following information):**
 - Platform:  Editor (Windows 10, x64)
 - Unity: 2019.3.7f1
 - SoftMaskForUGUI: 0.9.1#upm

**Comment by MartinHaeusler** [comment]
I just noticed something: when I use the "Fix" button to change the material, the changes get reverted. When I choose the material manually, it works!

**Comment by mob-sakai** [comment]
@MartinHaeusler 
Thank you for reporting!
