### ISSUE TITLE
UI batching is broken for SoftMaskable elements

### ISSUE THREAD

**Issue by Arkarit** [mob-sakai/SoftMaskForUGUI#76]
**Describe the bug**
SoftMaskable applies a cloned, modified unique material to each Graphic it belongs to. This breaks UI batching for all SoftMaskable elements completely.

**To Reproduce**
1. Create a parent container with a SoftMask
2. Add ~20 of TextMeshPro child elements with SoftMaskable
3. Play
4. Open and enable the Frame Debugger
5. In the frame debugger, examine the draw calls: Each SoftMaskable child element issues an own draw call!

Also, the issue can be examined in the Profiler (UI/Render, "Batch breaking reason: Different material instance") 

**Environment (please complete the following information):**
 - Platform: Windows 8.1
 - Unity: 2019.3.3f1 personal
 - SoftMaskForUGUI: v0.9.1

**Additional context**
The reason seems to be in SoftMaskable.GetModifiedMaterial().
For testing purposes, I simply added a dict to store already modified materials, which seems to fix the issue at first glance (but as I am not too deep into it, some additional checks might be necessary).
See attached patch.
[SoftMaskForUGUI-test-fix-batching.txt](https://github.com/mob-sakai/SoftMaskForUGUI/files/4463793/SoftMaskForUGUI-test-fix-batching.txt)

**Comment by Arkarit** [comment]
As more or less expected, the preliminary fix was not sufficient; an additional hash by SoftMask is necessary (see pull request)

**Comment by mob-sakai** [comment]
@Arkarit 
Thank you for reporting!
I'm planning to introduce the material cache used by UIEffect.
