### ISSUE TITLE
[Editor] Visual bug with ScreenSpaceCamera canvas and rotating the camera around

### ISSUE THREAD

**Issue by maskedmouse** [mob-sakai/SoftMaskForUGUI#78]
**Describe the bug**
In Editor when rotating the camera the softmask is kind of following around. as if it is not updated every frame but is behind a few frames.

**To Reproduce**
1. Create a canvas with ScreenSpaceCamera
2. Create a GameObject with a circle image and a SoftMask
3. Create a child with an image, set color to red and add SoftMaskable
4. Go into playmode
5. Rotate the camera
6. Observe the red color folowing around instead of being steady

**Environment (please complete the following information):**
 - Platform: Editor (WebGL target)
 - Unity: 2019.3.11f1
 - SoftMaskForUGUI: 0.9.1 [#upm branch]

**Additional context**
![Unity-2019 3 11f1-SoftMask-Bug](https://user-images.githubusercontent.com/3502325/80597726-8604ae00-8a28-11ea-8e6c-d0c9d543a2f2.gif)

I used an online mp4 to gif so the quality is bad but you can still see the effect I'm having in the editor.
I've got a script attached to the camera so that whenever I'm dragging around it will rotate. The camera itself stays on position 0,0,0. It just rotates around.
Not a 100% sure if this also happens in a build but it seems to be more steady in a webgl build. It's not super noticeable as in the Editor.

**Comment by mob-sakai** [comment]
@maskedmouse 
Thank you for the report!
Could you please attach a minimum repro project for this issue?

**Comment by maskedmouse** [comment]
Here's a zip containing a minimal project.
https://maskedmous.stackstorage.com/s/rutdEowxbi3gWi5

Go into play mode and use left mouse button to rotate the camera around

**Comment by mob-sakai** [comment]
Thank you, it is reproduced.
Honestly, I don't know how to solve it... X(

It seems to be stable when you operate the camera with inspector view.

**Comment by maskedmouse** [comment]
Well in a build it doesn't really seem to happen. So it is not a critical issue. But it does make me wonder, if the code under #if UNITY_EDITOR is causing the problem. I haven't gone through the script thoroughly to understand its behaviour. But since it runs well outside of the editor then there's a likely chance that there is a problem in the editor only code.

**Comment by mob-sakai** [comment]
@maskedmouse 
You're right.
Perhaps there is a problem with the code for the editor.

**Comment by mob-sakai** [comment]
WIP: I've solved it.
![](https://user-images.githubusercontent.com/12690315/80724199-868e6900-8b3c-11ea-9b55-3dc33dda15dd.gif)
