### ISSUE TITLE
Scrollview softmasked items are visible outside viewport mask

### ISSUE THREAD

**Issue by maskedmouse** [mob-sakai/SoftMaskForUGUI#82]
**Describe the bug**
I've added a scrollview to my canvas with a softmasked item as child of content.
However, the scrollview's viewport mask does does not occlude the softmasked items under content.
Am I doing something wrong or is it broken in 2019.3.x?

The eventual use case is a ScrollView in a scrollview with content that is softmasked.
Complicated layered UI. But a use case for my work.

**To Reproduce**
1. Go to Sample Scene
2. Go into play mode
3. scroll the list so that the item is half out of the viewport
4. observe scroll view items not being occluded (hidden) outside of the viewport

**Expected behavior**
Softmaskable items in a scrollview list outside of the viewport should be occluded

**Screenshots**
![Scrollview Softmask bug](https://user-images.githubusercontent.com/3502325/81179607-2f5c1e80-8faa-11ea-9a83-69af6e813c79.png)

**Environment (please complete the following information):**
 - Version: 0.10.0-preview.2
 - Platform: Editor Windows, WebGL
 - Unity version: 2019.3.12f1

**Additional context**
Project for reproduction
https://maskedmous.stackstorage.com/s/JYug7GMtoGk2THZ

**Comment by mob-sakai** [comment]
@maskedmouse 
Thank you for reporting!

**Comment by mob-sakai** [comment]
## Scroll View With Regular Mask Viewport

It was due to SoftMask ignoring the stencil.
I'll fix it later.

## Scroll View With Soft Mask Viewport

`UIMask` sprite has a small alpha.
- Set the softness parameter to 0.01.
- Or, use `UISprite` sprite instead of `UIMask` sprite.
![](https://user-images.githubusercontent.com/12690315/81256544-c76e0c80-906b-11ea-85a9-c91a81d02571.png)

**Comment by mob-sakai** [comment]
Action plans:

- Change the default value of the `Use Stencil` to true.
- If the parents contain some mask components, it is suggested to use stencil.
  - Some Mask components are found in the parents.  
Do you want to use stencil to apply the masks?
- If the UIMask is specified as a `Source Image`, it is suggested to use another image.
  - SoftMask does not recommend to use UIMask as a `Source Image`.  
Do you want to use UISprite instead?
