### ISSUE TITLE
WebGL demo broken

### ISSUE THREAD

**Issue by maskedmouse** [mob-sakai/SoftMaskForUGUI#83]
**Describe the bug**
The WebGL Demo is broken it has issues parsing the json from the webgl build.

**To Reproduce**
1. Go to [https://mob-sakai.github.io/SoftMaskForUGUI/](url)

**Screenshots**
![WebGL demo error](https://user-images.githubusercontent.com/3502325/81180379-3b94ab80-8fab-11ea-931a-88fc68f0737e.png)

**Additional context**
Seems to be broken since you updated the package to 0.10.0?

**Comment by mob-sakai** [comment]
@maskedmouse 
Thank you for reporting!
I fixed it now!
