### ISSUE TITLE
[critical] Bug build IL2CPP

### ISSUE THREAD

**Issue by stalker1hunt** [mob-sakai/SoftMaskForUGUI#84]
**Describe the bug**
I want build in IL2CPP and have bug. But i fixed his like:
Old
```
		protected override void OnValidate()
		{
			graphic.SetMaterialDirty();
			OnTransformParentChanged();
			base.OnValidate();
			_hasStencilStateChanged = false;
		}
```
new
```
		protected void OnValidate()
		{
			graphic.SetMaterialDirty();
			OnTransformParentChanged();
			_hasStencilStateChanged = false;
		}
```
With a new code bug has been solved. 

**To Reproduce**
1) Build

**Expected behavior**
Library\PackageCache\com.coffee.softmask-for-ugui@f5f5b7e3413b16a9f9ba8e27fcf7f22a0f82adac\Scripts\SoftMask.cs(417,27): error CS0115: 'SoftMask.OnValidate()': no suitable method found to override

**Screenshots**
http://prntscr.com/scg6mz

**Environment (please complete the following information):**
 - Version last
 - Platform: Android
 - Unity version:  2019.3.0f6
 - Build options:  IL2CPP

**Comment by maskedmouse** [comment]
`base.OnValidate()` is of `Mask` inside a `#if UNITY_EDITOR`. When you build for Android the `base.OnValidate` method won't exist resulting into a build error.

**Comment by mob-sakai** [comment]
@stalker1hunt  @maskedmouse 
Thank you for reporting.
I'll fix it ASAP.
