### ISSUE TITLE
UI block canvas + mask effect

### ISSUE THREAD

**Issue by salonsoGH** [mob-sakai/SoftMaskForUGUI#88]
Hi, 

How can I achieve this effect? 

![image](https://user-images.githubusercontent.com/57361118/83160786-e9f1c380-a107-11ea-87e1-0cfa69bdfd53.png)

Everything darkens and not clickable and the circle clickable. 

I have been trying but cannot get it working. 

Regards.

**Comment by mob-sakai** [comment]
@salonsoGH 
Yes, perhaps it is possible.
Give me a minute.

Or: Try this solution.
https://github.com/mob-sakai/UnmaskForUGUI

**Comment by mob-sakai** [comment]
Use `SoftMaskForUGUI v1.0.0-preview.3` or later.

![](https://user-images.githubusercontent.com/12690315/83714668-620b3c80-a666-11ea-93c8-c5990bec0f50.gif)

- Hierarchy  
![](https://user-images.githubusercontent.com/12690315/83713768-f6c06b00-a663-11ea-824a-ba11492cb57d.png)
- Inspector
![](https://user-images.githubusercontent.com/12690315/83713773-f922c500-a663-11ea-857d-656cab39c54b.png)

**Comment by salonsoGH** [comment]
I will have a look, thanks!
