### ISSUE TITLE
button or input-field will not working

### ISSUE THREAD

**Issue by YenYaoHan** [mob-sakai/SoftMaskForUGUI#89]
Hi there ,
First , thanks for your great work!
i implement that sdk into my project, for now working well,
but sometimes when i add SoftMaskable component in to button or input-field ,it was lost click function.
![image](https://user-images.githubusercontent.com/17308097/83216893-f2480e00-a19c-11ea-9b3c-0ce017f60b09.png)

 - Version v0.9.1
 - Platform: Windows
 - Unity version: 2018.4.13f1
 - Build options: mono,.Net 4.x

**Comment by mob-sakai** [comment]
@YenYaoHan 
Thank you for your reporting!
Could you please attach a minimal project that reproduces the issue?

**Comment by mob-sakai** [comment]
@YenYaoHan 
Try use `v1.0.0-preview.3`.
