### ISSUE TITLE
Performance Problems on Android

### ISSUE THREAD

**Issue by NikittyS** [mob-sakai/SoftMaskForUGUI#91]
Hello. I have performance problems on Android - FPS drop from 59 to 47 when enable UI object with SoftMask.

**Problem**
- Drop FPS on Android device

**Environment**
- Device: Nexus 5
- Platform: Android 6.0
- Unity: 2019.3.0f6
- SoftMaskForUGUI: 1.0.0-preview.3

**To Reproduce**
1.  Create Canvas
2.  Create parent Image with SoftMask
3.  Create child Image inside parent

This problem doesn't only on Nexus 5. I tried on other devices with Android 9.0 and the problem was the same. But fps depends on the performance of the device.

P.S. On iOS works perfectly.

**Screenshots**

Unity:
<img width="150" alt="Hierarchy" src="https://user-images.githubusercontent.com/60339254/83740870-c7792080-a69a-11ea-8835-645559290997.png">
(Zoom_Under just copy of Zoom_Inside)
<img width="250" alt="CanvasMain" src="https://user-images.githubusercontent.com/60339254/83740853-c21bd600-a69a-11ea-9ad2-159d7cc3d80f.png">
<img width="250" alt="Parent" src="https://user-images.githubusercontent.com/60339254/83740873-c8aa4d80-a69a-11ea-893c-034a5be70bde.png">
<img width="250" alt="Child" src="https://user-images.githubusercontent.com/60339254/83740869-c6e08a00-a69a-11ea-9f85-fb88efafaa94.png">

Nexus 5:

Object with SoftMask - disabled
<img width="250" alt="maskOff" src="https://user-images.githubusercontent.com/60339254/83740871-c811b700-a69a-11ea-8914-5e58fb7a0793.jpg">
Object with SoftMask - enabled
<img width="250" alt="maskOn" src="https://user-images.githubusercontent.com/60339254/83740872-c8aa4d80-a69a-11ea-875a-75954b440ced.jpg">

Can you help with that problem? Thank you!

**Comment by mob-sakai** [comment]
@NikittyS 

- Change `Desampling Rate` to `x1` or `x2`
- Another solution: https://github.com/mob-sakai/UnmaskForUGUI

If the soft mask buffer is being updated every frame, it's probably a bug.
Could you please attach a minimal project that reproduces the issue?

**Comment by NikittyS** [comment]
@mob-sakai 

Hello. I'm tried set `Desampling Rate` to `x2`, it give 49-50 fps (from 59).

I made one mistake when I said about fps falling with only one object with SoftMask. One object doesn't reduces fps, but two objects reduces.

**Minimal project**
[SoftMaskTest.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/4733617/SoftMaskTest.zip)

**Comment by mob-sakai** [comment]
It's interesting.

On my Android device (Sony Xperia XZ), FPS didn't drop.
So I added 20 SoftMask, FPS dropped to 30.

**Comment by NikittyS** [comment]
In main project, I have around 150 movable objects with SoftMask. On my `iPhone 6s` stable 60 fps, but `Nexus 5` show ~20-25 fps.

**Comment by mob-sakai** [comment]
I improved performance.
- The pixel shaders in SoftMaskable shaders has been optimized.
- Add a new option to ignore stencil if it is not needed as a mask.

it gives 45-47 fps (from 30, with 20 SoftMasks).

**Comment by mob-sakai** [comment]
Try to use `v1.0.0-preview.4`

**Comment by NikittyS** [comment]
@mob-sakai 
Hello. Good work! Thank you! Nexus 5 with ~150 object now give 50 fps, that's good.

But I have one more little issue - when I'm update `SoftMask`  to `1.0.0-preview.4` soft mask doesn't work when `Canvas Render Mode` set to `Screen Space - Overlay`, but when I'm set it to `Screen Space - Camera` mask work well.

**Comment by mob-sakai** [comment]
Thank you for testing, @NikittyS .

I tested it on a project you previously uploaded. ([SoftMaskTest.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/4733617/SoftMaskTest.zip))
- Set `Canvas Render Mode` to `Screen Space - Camera`
- Set `Render Camera` to `Main Camera` in the scene

However, the problem did not reproduce in my environment...
- Editor (on Mac)
- Android 8.0 (Sony Xperia XZ)

Could you please attach a minimal project that reproduces the issue?

**Comment by NikittyS** [comment]
@mob-sakai 

Hmm, I restarted Unity and everything was fine, sorry for this mistake. 

Thank you for this best soft mask!
