### ISSUE TITLE
TextMeshPro not work  TMP_SubMeshUI (Enable Bold)

### ISSUE THREAD

**Issue by Avatarchik** [mob-sakai/SoftMaskForUGUI#94]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Version [e.g. 1.0.0]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2018.2.8f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, LWRP]

**Additional context**

**Comment by arenart99** [comment]
Temporarily I added a "if" check in SoftMaskable.cs (line 285)
`          var current = this;
            UnityEditor.EditorApplication.delayCall += () =>
            {
                if (!current) return;
                if (!graphic) return;
                if (graphic.name.Contains("TMP SubMeshUI")) return;
                if (!graphic.material) return;
                if (!graphic.material.shader) return;
                if (graphic.material.shader.name != "Hidden/UI/Default (SoftMaskable)") return;

                graphic.material = null;
                graphic.SetMaterialDirtyEx();
            };`

**Comment by mob-sakai** [comment]
@Avatarchik @arenart99 
Thank you for your cooperation.
