### ISSUE TITLE
Soft mask incorrect filtering in editor view

### ISSUE THREAD

**Issue by SamuelHyman** [mob-sakai/SoftMaskForUGUI#95]
The editor view for a soft masked image does not match its in game view.  I'm using 2019.4 LTS with the 1.0.0 preview.5 version of soft mask in URP.  Is there a way to disable the editor filtering, is this a user error?

![question](https://user-images.githubusercontent.com/4791708/85973897-c1284c80-b999-11ea-852a-dcd4f294df1a.png)

**Comment by mob-sakai** [comment]
@SamuelHyman 
Thank you for reporting and sorry for my late reply.

I would like to know more about this issue. 
Could you please attach a minimal project (included Assets and ProjectSettings directory) that reproduces the issue?

**Comment by mob-sakai** [comment]
Perhaps this is due to PixelPerfect.
