### ISSUE TITLE
Shadow Flickering Behaviour

### ISSUE THREAD

**Issue by dvillaverdedrakhar** [mob-sakai/SoftMaskForUGUI#96]
We are experiencing a strange shadow flickering behaviour on Nintendo Switch. We think it could be related to the SoftMaskForUGUI plugin, because, when this flickering is taking place, there are SoftMask UI elements on screen.

We let you here 5 GIFs (out of context due to confidentiality contracts) exampling what we are suffering.

https://gyazo.com/aa9428afa0c2240e1ba972c2819cd6f8
https://gyazo.com/14b9d213e95d0f9d18b0fabd575e791e
https://gyazo.com/8d0c427e8a106c8d9bb4de715915b9ac
https://gyazo.com/e1c406379343c266e66a276f2a430d34
https://gyazo.com/25058bb75085e18054d506832ae4400f

------------------
Environment:
Nintendo Switch SDK 9.4.1
Unity 2019.3.0f5
Addressables 1.7.4
SoftMaskForUGUI 0.9.0

**Comment by mob-sakai** [comment]
@dvillaverdedrakhar 
Could you please attach a minimal project that reproduces the issue?

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
If the same issue arises, please re-open this issue.
