### ISSUE TITLE
Clickable area inverted in iOS

### ISSUE THREAD

**Issue by mburdom** [mob-sakai/SoftMaskForUGUI#97]
Whenever you create a Maskable with SoftMask as childs if you try to click through any of the SoftMask childs the clickable area positions itself incorrectly in iOS due to the coordinations being inverted in the Y axis (we tested changing the SystemInfo.graphicsUVStartsAtTop comprobation in SoftMask script to return true in iOS and it worked fine).

**Steps to reproduce**
1. Create a Maskable parent
2. Create a SoftMask which you can click through
3. Create some clickable options in different positions in the same Y axis.
3. Re-position in runtime in front of on of the clickable Game Objects.
4. You can see that in Android works fine but in iOS the clickable area doesn't correspond with the mask area.

**Expected behavior**
The clickable area is the same of the visual mask area.

**Environment**
Platform: iOS
Unity Engine 2019.3.5f1

**Comment by mob-sakai** [comment]
@mburdom 
Could you please attach a minimal project that reproduces the issue?

**Comment by mob-sakai** [comment]
fixed in `v1.0.0-preview.12`
