### ISSUE TITLE
Option to disable softening completely

### ISSUE THREAD

**Issue by BenWoodford** [mob-sakai/SoftMaskForUGUI#98]
**Is your feature request related to a problem? Please describe.**
The below happens when using a hard-edged mask (Unity's own mask doesn't support overlapping masks where it only masks the children, so having two images "splitscreen" style diagonally isn't terribly easy)

![image](https://user-images.githubusercontent.com/503263/88292810-066a4080-ccf2-11ea-8b8a-4f1dee7271a3.png)

The masks for context

![image](https://user-images.githubusercontent.com/503263/88292847-141fc600-ccf2-11ea-88c4-024ad6b11118.png)

Even at 0.01 softness it gives a soft-edged look.

**Describe the solution you'd like**
The option to completely disable softening and just utilise the other features of the component (like the better hierarchical masking)

**Comment by mob-sakai** [comment]
@BenWoodford 
Try increasing the texture resolution of the `SpellMask-***`.

**Comment by BenWoodford** [comment]
They were 1024x1024 so already pretty big. However more curiously, as had switched back to using Mask and only masking one half of the square (and toggling it as necessary)... when I switched back to the soft mask it suddenly isn't working and the buffer shows nothing in it. That's weird...

![image](https://user-images.githubusercontent.com/503263/89275192-da2bb980-d639-11ea-9300-ede5878dc76c.png)

**Comment by mob-sakai** [comment]
I would like to know more about this issue. 
Could you please attach a minimal project (included Assets and ProjectSettings directory) that reproduces the issue?

**Comment by mob-sakai** [comment]
If you want a hard edge, Unity Default Masks are the easiest option:

![](https://user-images.githubusercontent.com/12690315/90351574-9f834180-e07b-11ea-98d7-70026d947ad9.png)
![](https://user-images.githubusercontent.com/12690315/90351854-8202a780-e07c-11ea-89cb-f669a2cd1db7.png)

**NOTE:** Set the `Filter Mode` to `Pointer (no filter)` in the import settings of mask textures.

[issue98.unitypackage.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/5081853/issue98.unitypackage.zip)

**Comment by BenWoodford** [comment]
I’ll see what I can do but as it occurred randomly I’m not sure how easy it’ll be to recreate it in a stand-alone project. Using Unity masks isn’t really viable in all scenarios as Unity doesn’t obey hierarchies for masks - two siblings will act as one mask I’ve found. Whereas your system does obey the hierarchy and only mask children

**Comment by mob-sakai** [comment]
Sorry for late reply.
It seems desirable to support `Softness=0`.
