### ISSUE TITLE
[v1] Always Include TextMeshPro Shaders

### ISSUE THREAD

**Issue by sp-alberto-uriarte** [mob-sakai/SoftMaskForUGUI#99]
I spent all day trying to figure it out why my text didn't appear on device (iOS and Android) but worked perfectly on Editor.
It turns out that TMP shaders were not added in the build since nobody was referencing it.
To fix it, I added TMP shaders to the list of "Always Included Shaders" located at "Edit > Project Settings > Graphics"

Not a bug per se, but I think reporting it may help other people that is experiencing this issue

**Comment by mob-sakai** [comment]
@sp-alberto-uriarte 
Thank you for your reporting!

Yes, the TMP shaders should be included in the build:

- Always Included Shaders (as you mentioned)
- Preloaded Asset
- Resources folder

I will fix it later.

**Comment by novavision** [comment]
Still exists in preview 14

**Comment by novavision** [comment]
Still exists in preview 14

**Comment by mob-sakai** [comment]
👀

**Comment by mob-sakai** [comment]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
